### ISSUE TITLE
backup/restore homegear config

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#1041]
homegear is a SW-only gateway into the HomeMatic and MAX! device world, both of which are popular and in wide use in Germany. It stores data of learnt devices into `/etc/homegear` and `/var/lib/homegear` see https://doc.homegear.eu/homegear/backup.html. I don't know if we can force it to have its config elsewhere such as say below $OPENHAB_USERDATA.

@BClark09 do you think we could add this to openhab-cli backup/restore ?
It's hard for people to understand that openhab-cli does not take care of this relevant config for openHAB devices just because it is config located outside openHAB.

**Comment by BClark09** [comment]
> @BClark09 do you think we could add this to openhab-cli backup/restore?

`openhab-cli backup` is only a shortcut to `$OPENHAB_RUNTIME/bin/backup`. Personally, I think that since it's not openHAB's responsibility, it shouldn't be backed up inside of openHAB's scripts. Secondly, the backup script(s) should work identically the same on any OS, and ideally should be restored on any different machine. Am I right in thinking homegear is only a Linux software?

One thing we could do is be a little more clear on what `$OPENHAB_RUNTIME/bin/backup` does not back up. We can do this during the "Okay [y/n]" prompt.

**Comment by mstormi** [comment]
thanks for your feedback.
I decided to put that into the Amanda backup now, see #1042
