### ISSUE TITLE
Editing openhabian.conf with a Windows editor

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#1051]
e.g. for WiFi boot is said to break it.

Either confirm it works or fix it.

**Comment by ecdye** [comment]
Probably true because of line endings but I did not check.

**Comment by mstormi** [comment]
I was thinking the same. Should we reword the installation docs ?

**Comment by ThomDietrich** [comment]
Hola,
many years I implemented a fix for that. Windows editors shouldn't be an issue
https://github.com/openhab/openhabian/blob/master/build-image/first-boot.bash#L31
In fact, the file should have Windows line endings (`\n\r`) when created, so that all users can edit it without issues

**Comment by mstormi** [comment]
> In fact, the file should have Windows line endings (`\n\r`) when created

It might no longer have as we messed with openhabian.conf* and .dist recently when working on the CI pipeline
Then again I just opened /boot/openhabian.conf from Windoze and it looks fine, and IIRC it should work fine with or without \r due to your fix.

So most likely there's no problem but the guy to report that messed up something. I will close this and reopen if there's news. Thanks Thomas

**Comment by ThomDietrich** [comment]
What I think was happening here: The default Windows editor does not deal with linux files properly. That's why the file would look broken on Windows and it would likely become invalid if changed and saved. An example and the claim that this has been fixed by MS: https://devblogs.microsoft.com/commandline/extended-eol-in-notepad/

Imho leave it like it is but implement a conversion from unix to windows in the image creation script if this is still an issue for users. :)

Btw really happy to see you guys kick it off!
Best! th

**Comment by mstormi** [comment]
Just flashed latest image and opened openhabian.conf with notepad but LGTM
