### ISSUE TITLE
git --tags giving errors

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#1057]
e.g. on Homegear installation but I guess elsewhere as well

++++ git -C /opt/openhabian describe --tags --abbrev=0
fatal: No tags can describe '565bf0bd52329ef7623ac60b6718af5c55befaf6'.
Try --always, or create some tags.

**Comment by mstormi** [comment]
forget it.
It was because openhabian.conf contained my private branch (which does not have tags).

Then again that's what the most recent image build gave me. I think we still have a bug there, it should point to stable instead.

**Comment by ecdye** [comment]
No, it points to whatever branch it was run from. I have had zero issues with it pointing to the wrong branch.

**Comment by mstormi** [comment]
The openhabian.conf of/from the image should have clonebranch=stable burnt in, that we need to change.

**Comment by ecdye** [comment]
no, it needs to be whatever the PR or branch it was originated from otherwise testing does not work correctly, if you trigger a build on the stable branch it works as expected. See <https://github.com/openhab/openhabian/pull/985#issuecomment-665181530>. Without the branch set to the value when triggered, tests would point to a branch that is incorrect and make it pointless. Image builds are made for devs. If we want a stable branch build we trigger one on the stable branch.

**Comment by mstormi** [comment]
I wasn't aware of that but ok (now that I know I can edit it before boot).
But then pay attention to not point users at beta images.

**Comment by ecdye** [comment]
Yes I am aware.
