### ISSUE TITLE
[srv_bind_mounts] srv_bin_mount are read-only on debian 10.6

### ISSUE THREAD

**Issue by TBail** [openhab/openhabian#1221]
## Issue information:
I am using Debian 10.6 in a virtual machine. openhabian ist a template to setup the system. So in facht my system is not an openhabian system, but it is based on openhabian.

I found that the se´rv_mount_binds under /srv/openhab-... are read only by default. I do not know if that is an intention or if that is an error. If the folders are rw than it is possible to use /srv/... as a central point to access all files from open hab und use them in smb-con instead of the "real" folders.

## Debug information:
Just try to create a new file under /srv/openhab-logs an what happen

## Possible solution:
Modify the mount-template from the include folder. Add a ",rw" in line Options=bind so that the new line is:

`Options=bind,rw`

This should fix the problem

**Comment by mstormi** [comment]
Cannot reproduce your issue on a fresh RPi install. It's also 10.6 and /srv/* are mounted rw by default.
openHABian does not pass any special options to mount so you should get the default for the filesystem type which is rw for almost ever fs type.
So probably your "is based on" rather than "is" screwed up something ? Some /srv exports are loopbacks of dirs which are on ZRAM. You fail to mention what HW arch your box is but I'd suspect ZRAM isn't running because it's no RPi.

**Comment by TBail** [comment]
As said i use openhabian as a template. My machine is a synology and the arch is x86 and i am using avirtual machine. Yes ZRAM is not running. 

The setup is fresh and i checked with an older setup where i see the same thing.

Maybe i missed something, but my question in the community produced no valid results. I see two option:

1.) Leave the system as it is 
2.) Add the rw option 

I tend to setup new systems regularly and this is now in my documentation. I am sure will will check the openhabian sources again to learn some new things.
