### ISSUE TITLE
Mosquitto (option 23) installation failed

### ISSUE THREAD

**Issue by BobRak** [openhab/openhabian#1343]
openhabian version 1.6.1-1021 [stable]

[14:59:44] openhabian@openhabRpi4:/var/log/openhab2$ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
[15:07:06] openhabian@openhabRpi4:/var/log/openhab2$ uname -m
armv7l

openhabian would end this task with a failure message (sorry I don't have a copy or it anymore) 

Looking at journalctl I found
`Dec 28 14:54:59 openhabRpi4 mosquitto[9361]: 1609196099: Error: Unable to open log file /var/log/mosquitto/mosquitto.log for writing
Dec 28 14:54:59 openhabRpi4 systemd[1]: mosquitto.service: Main process exited, code=exited, status=1/FAILURE
`

Adding the directory /var/log/mosquitto resolved the issue.

PS I am using 1.6.1 instead of 1.6.2 because I want to setup an openhab v 2 system for testing.

**Comment by ElD4n1** [comment]
I now have the same issue on 1.6.2 on a fresh install after a power outage.
In the beginning it worked for about three days, but after the improper shutdown i now have this issue, so I suspect it could maybe have something to do with ZRAM because it was not able to execute its shutdown tasks? Just a guess. 

I commented out the line
`log_dest file/var/log/mosquitto/mosquitto.log`
 in /etc/mosquitto/mosquitto.conf as temporary workaround.

Time to add a USV for me.

**Comment by brangc** [comment]
Unsubscribe

Daniel Hofer <notifications@github.com> schrieb am Do. 31. Dez. 2020 um
22:09:
