### ISSUE TITLE
Kernel panic after updating Openhab3

### ISSUE THREAD

**Issue by PottiMc** [openhab/openhabian#1420]
## Issue information:
I tried to update my Openhab 3 installation via the Openhabian-Config tool. That failed in the end, but no error message was provided. So I used apt-get upgrade. Now my Pi won't boot at all, telling that a "firmware is not found". 
It doesn't even pull an ip adress over ethernet or wifi, so I connected it to my TV to check what's going on. 
Attached you can see the error messages. What can I do to fix this?
![index](https://user-images.githubusercontent.com/39881308/104710850-db046380-5720-11eb-980f-5f767f78a873.jpg)
![index2](https://user-images.githubusercontent.com/39881308/104710856-dcce2700-5720-11eb-889c-a94d0d20c168.jpg)

## Debug information:
Since I can't access the file system at all at the moment there's no debugging possible atm.

## System information:
Pi 4 4GB
Openhab 3 Snapshot

**Comment by mstormi** [comment]
I'm sorry but that's not an openHABian issue (it just installs Raspberry Pi OS packages and those have caused your problem).

**Comment by MattB12** [comment]
I also have this issue after running an update from inside the openhabian config tool.
![20210324_154146](https://user-images.githubusercontent.com/48497470/112257219-9d8bfb80-8cb8-11eb-9015-52dae2b5114b.jpg)

**Comment by rreuter-dgtest** [comment]
+1. 

All due respect, providing a menu option that provides no confirmation option and subsequently bricks your installation _is_ an OpenHABian issue.

**Comment by mstormi** [comment]
> providing a menu option that provides no confirmation option and subsequently bricks your installation _is_ an OpenHABian issue

No. openHABian just installs RasPi OS packages so it has no knowledge about or influence on what's going to happen when you
select the menu option.
If any of the packages is so broken that it bricks the system (haven't seen any such to date but even if there was) it's an issue with the package at best, or with the HW or anything but not openHABian itself.
And the OP is unclear about what exactly he did or what the (openHABian) error was so how do you know there was no confirmation being asked for ? That he didn't ignore some important output ?
Note it's unclear what bricked the OP's box. He wrote he *manually* used apt-get upgrade AFTER using the openHABian menu and BEFORE it was bricked so the implications were due to his action and clearly openHABian cannot take any responsibility for that. Note it does not happen on stock openHABian/Raspi OS in thousands of installs so it's pretty likely a problem specific to the OP, his HW or handling. And all due respect but there's nothing we can do about that.
