### ISSUE TITLE
Add Conbee + Phoscon support

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#1473]
a popular Zigbee controller + companion app
https://phoscon.de/de/conbee2/install#raspbian
Note phsocon "app" requires an apache2 and runs on port 80

Latest deCONZ @ http://deconz.dresden-elektronik.de/raspbian/deconz-latest.deb

**Comment by bdvrieze** [comment]
For what I can help...

These are the steps I followed:

for openhabian on RPI4, connected on a non powered usb hub (had issues on USB3, and the other port is taken by a serial controller (prolific 2303) and I have a zwave controller connected on the hub...
conbee II
http://deconz.dresden-elektronik.de/raspbian/deconz-latest.deb
sudo dpkg -i deconz-latest.deb
sudo apt update
sudo apt install -f
sudo reboot
cd /lib/systemd/system
sudo nano deconz.service
- port changed to 8070
sudo systemctl enable deconz
sudo reboot

**Comment by eX00r** [comment]
I found that changing only the port might not be enough and suggest to edit deconz.service as follows:

```
sudo nano /lib/systemd/system/deconz.service
```

change the port to your desired port and remove the 

> -platform minimal

https://community.openhab.org/t/oh-webinterface-not-rechable/119378/7

**Comment by guy-inkognito** [comment]
+1 that it'd be great to have this!

Just to share two thoughts:

- Per default openhab service is using port 8080, thus is not conflicting with default port 80 of Phoscon app. I'm running both in default config and don't experience any trouble. However, it may be a bit counterintuitive for people to access via http without port and land on the Phoscon app rather than the OH app though ;)
- There is an option to also access the deCONZ GUI application, even when running deCONZ in headless mode, by utilizing TigerVNC. Works like a charm: https://peterkieser.com/2020/11/23/deconz-vnc-access-without-full-blown-xorg-install/. Maybe it's possible to also automatically set up this. From what I read in the community, not knowing how to set up this is what makes people use another Raspbery.
