### ISSUE TITLE
License

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#1555]
Just noticed Github shows openHABian as licensed under "ISC".
 (Internet Software Consortium? Those famous creators of BIND, one of the most buggy systems ever? SCNR)

We need to change that (not sure how, simply create LICENSE.md ?). openhab-core is shown as EPL2 but not sure if that's correct either.

**Comment by ecdye** [comment]
The problem is that we cannot change the license without approval from every prior contributor. The license is fine it is simply a more succinct version of the MIT license. There are definitely legal repercussions of changing the license and I'm not a lawyer and would prefer not to open us or by extension the openHAB project to legal prosecution.

**Comment by mstormi** [comment]
Hmm, I wonder why a license change in general would require *all* contributors to agree (which would not work in any major OSS project whatsoever, would it) and if that's true.
Then again as you think the current license is fine I don't want to open Pandora's box on that either so let's forget about this for the time being.

**Comment by ecdye** [comment]
It does work, Firefox did it several years ago.
