### ISSUE TITLE
Default username/password with Openhabian v1.7.5

### ISSUE THREAD

**Issue by arch1v1st** [openhab/openhabian#1746]
Hello,

It seems the latest Openhabian release (v1.7.5, 32-bit) has a different username/password for accessing SSH which was previously 'openhabian:openhabian' by default, and doesn't prompt to set one during installation.  I appreciated how streamlined the install process was, but couldn't login after the fact.  After fighting with it, rolled back to 1.7.4b, which prompted me to set the password during install before kicking off its automatic system updates.  Up and running now!  Openhabian ROCKS!

Hopefully this helps to save others some time and frustration too. :)

**Comment by bohni** [comment]
I also started with a fresh 3.4.0 Openhab by flashing Openhabian 1.7.5

I can open the browser at openhabian:8080 and run through the setup - set location, select addons etc.  I also can open settings to start set up my model and so on.
Running "ssh openhabian@openhabian" leads to login, but the password 'openhabian' is not accepted.

With fresh flashed 1.7.4b login via ssh is possble before openhab-initilaize is finished (no connection to port 8080 via browser)

**Comment by bohni** [comment]
https://github.com/openhab/openhabian/blob/4d13f4baffe09c04629d4086711a4ec032f8ccf1/build-image/first-boot.bash#L59

sets the username (if the car was empty, then a default is used)

that leads to 

https://github.com/openhab/openhabian/blob/4d13f4baffe09c04629d4086711a4ec032f8ccf1/build-image/first-boot.bash#L68

that is a OR expression with `[ -v $username ]` allways being `true`, because the var was set before.

So the chpasswd is always skipped.

**Comment by bohni** [comment]
OK. Did another fresh image install on the sdcard.

This time ssh with openhabian:openhabian did work.

**Comment by mstormi** [comment]
Ok. Thanks for pointing me at the change that caused this issue.
