### ISSUE TITLE
Influx instalation on latest Raspbian fails

### ISSUE THREAD

**Issue by bittmanv** [openhab/openhabian#1753]
## Issue information:
I was started new instalation on RPi4/4GB machine to SD Card to migrate my "home/production" RP3 to new HW,
Successfully downloaded image (openhabian-pi-raspios64-202212201355-gitb2e396e-crcbd182bf5.img.xz), extracted to SD Card and installed. After finishing of main part instalation, I started with optional components via openahbian-config, mqtt/mosquitto. 
But Influx+grafana failed, after enabling debug I received error message about invalid public key, see bellow error from later apt update. 
It took just 4 hours to find following link , where is noticed that Yesterday influx rotated keys.
[https://www.influxdata.com/blog/linux-package-signing-key-rotation/](url)
During my retrties I also used older Raspbian image (openhabian-pi-raspios64-202208152014-gitbe9d23e-crc8b028846.img.xz ) and issue was there as well. **I assume that also updating users will be affected**

I also found some workaroud with follwing procedure
1) Install new Certificate based on influx above ( start in home directory)
`cd`
`wget -q https://repos.influxdata.com/influxdata-archive_compat.key`
`cat influxdata-archive_compat.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/influxdata-archive_compat.gpg > /dev/null`
`echo 'deb [signed-by=/etc/apt/trusted.gpg.d/influxdata-archive_compat.gpg] https://repos.influxdata.com/debian stable main' | sudo tee /etc/apt/sources.list.d/influxdata.list`

2) now try to install Influx+grafana via openhabian-config, it will fail  ( this will create /etc/apt/sources,list.d/influxdb.list ),
4) edit file influxdb.list
`deb [signed-by=/etc/apt/trusted.gpg.d/influxdata-archive_compat.gpg] https://repos.influxdata.com/debian bullseye stable
`

run apt-get update
5) start openhabian-config Influx+Grafana again, now it should pass. ( at least for me it worked)

I'm not sure, if this issue can be fixed by modification of Openhabian image or is neccesary to wait for all respositories to be updated.

## Debug information:

openhabian@openhabian3:~ $ sudo apt-get update
Hit:1 http://davesteele.github.io/comitup/repo comitup InRelease
Hit:2 http://archive.raspberrypi.org/debian bullseye InRelease
Hit:3 http://security.debian.org/debian-security bullseye-security InRelease
Hit:4 http://deb.debian.org/debian bullseye InRelease
Hit:5 https://repos.influxdata.com/debian stable InRelease
Get:6 https://repos.influxdata.com/debian bullseye InRelease [7,022 B]
Hit:7 https://deb.nodesource.com/node_16.x bullseye InRelease
Hit:8 http://deb.debian.org/debian bullseye-updates InRelease
Hit:9 https://openhab.jfrog.io/artifactory/openhab-linuxpkg stable InRelease
Get:10 https://pkgs.tailscale.com/stable/raspbian buster InRelease
Err:6 https://repos.influxdata.com/debian bullseye InRelease
  **The following signatures couldn't be verified because the public key is not available: NO_PUBKEY D8FF8E1F7DF8B07E
Reading package lists... Done**
W: GPG error: https://repos.influxdata.com/debian bullseye InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY D8FF8E1F7DF8B07E
E: The repository 'https://repos.influxdata.com/debian bullseye InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

```

## System information:
Please tell us what OS you are running (Raspberry Pi OS, Debian, Ubuntu), what
HW you are running on (Raspberry Pi, amd64). Also include the output of

I was running installation in RPi4/4GB + 64GB SD Card  
`cat /etc/os-release` and `uname -m`.
```

PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
uname -m
aarch64

```

Regards, Vaclav

**Comment by mstormi** [comment]
I've exchanged the key link for the new one... can you try to
* deinstall influx
* start openhabian-config, let it update
* switch to main branch
* reinstall influx from the menu

**Comment by bittmanv** [comment]
Hi, 
My uninstalation of influx failed, package is gone, but service file is still there and openhabian config doesn't install package.
I will not have time to generate new fresh instalation till friday.

**Comment by mstormi** [comment]
Thanks for validating

**Comment by stif** [comment]
i stumbled across the same error, and i am still on `release` branch.

Since the old key is not working any more, it would be great to backport the new keyname in the OpenHAB3 Branch as well.

I created a pull request for the new key name in `release/openHAB3` branch: https://github.com/openhab/openhabian/pull/1763

**Comment by mstormi** [comment]
That doesn't make sense. The main branch which has the fix is forwarded to the openHAB3 branch at times when there's important things that need fixing. This I consider not to be important as it only affects few.
Anyone who wants to use it today can switch to main branch.

**Comment by mstormi** [comment]
Your willingness to help others is well appreciated, but technically this isn't how things can work.
Nobody can have both, stable *and* dynamic at the same time. It's a contradiction in itself.
So if there's external events such as Influx to change their repo key that you want to react to instantly, you must not use the release "stable" branch. You have to select main.

**Comment by stefan-hoehn** [comment]
Markus, I tried to setup OH(4) from scratch, which is why I 
- installed the latest openhabian-release https://github.com/openhab/openhabian/releases/tag/v1.7.5 -> resulting into 3.4.4
- openhabian-config is on openHABian Configuration Tool — [main]{2023-05-25T01:23:54-05:00}(606c74a)
- I disabled zram (to make sure that influxdb later has the right permissions when reenabling) it
- I then installed (24) influx / grafana which results into the below issue (I have enabled debug)

``
+ apt-get update
Get:1 http://davesteele.github.io/comitup/repo comitup InRelease [4,659 B]
Hit:2 http://deb.debian.org/debian bullseye InRelease
Hit:3 http://deb.debian.org/debian bullseye-updates InRelease
Hit:4 http://security.debian.org/debian-security bullseye-security InRelease
Hit:5 http://archive.raspberrypi.org/debian bullseye InRelease
Hit:6 https://repos.influxdata.com/debian bullseye InRelease
Hit:7 https://deb.nodesource.com/node_16.x bullseye InRelease
Hit:8 https://openhab.jfrog.io/artifactory/openhab-linuxpkg stable InRelease
Fetched 4,659 B in 2s (2,335 B/s)
Reading package lists... Done
+ return 0
+ cond_redirect apt-get install --yes -o DPkg::Lock::Timeout= influxdb
+ [[ -n '' ]]
+ echo -e '\n\033[90;01m$ apt-get install --yes -o DPkg::Lock::Timeout= influxdb \033[39;49;00m'

$ apt-get install --yes -o DPkg::Lock::Timeout= influxdb
+ apt-get install --yes -o DPkg::Lock::Timeout= influxdb
E: Could not get lock /var/lib/dpkg/lock-frontend. It is held by process 3087 (unattended-upgr)
N: Be aware that removing the lock file is not a solution and may break your system.
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?
``

Noticing **unattended-upgr** I rebooted and stopped OH.

The only way to get it working was to actually to reboot and then stop openhab. Does that make sense?
It is a pity that I did both, so I am not sure what fixed it.

**Comment by mstormi** [comment]
> Does that make sense?

Sort of, rebooting will probably have removed the lock. Whyever it was there in the first place.
