### ISSUE TITLE
Somehow mange to have static names on USB devices like z-wave sticks and such

### ISSUE THREAD

**Issue by skatun** [openhab/openhabian#184]
Prompt the user to plug in a new device, then map this to a synonym so that it later can be unplugged and swapped around.

[(https://wiki.debian.org/HowToIdentifyADevice/USB)]

**Comment by EliasGabrielsson** [comment]
@mstormi @holgerfriedrich Do you have some clever input on this??

If we could come up with some sleek solution that could really improve the core experience for linux newcomers trying out openHAB. I do personally also struggle with this issues sometime.

**Comment by mstormi** [comment]
Mmh, I'm a bit cautious on these things as I know that a openhabian implementation would signal it's easy and idiot-proof to use while in fact it is not. The boot process and dynamics what happens if you plug devices to map device pathes is highly complex and any automatism (which we would de facto need to implement in openhabian) is very much prone to error.
I had lengthy discussion with skatun who found it too difficult to mount a disk (for the purpose of placing backups there). He's a Windows guy who doesn't really understand the difficulties of implementations in Linux.  But the fact that even Linux experts like ourselves sometimes struggle with this is a strong hint that it is not easy at all.
While we could build _something_ to eventually cover a subset of cases, this is likely to be unreliable and therefore dangerous..
E.g. think of ZWave: I for instance have a RPi hat which in fact is not hot-pluggable but you must shutdown the box for (un)plugging. Any boot sequence and HW change (such as to plug in or out another of your sticks has the potential to result in a need to recalculate links).

**Comment by holgerfriedrich** [comment]
Not sure if I can help here. I am doing this using udev rules specific to my devices and thus hard to generalize. It is not only about being able to hotplug devices, sometimes you add a new device and after next reboot everything is screwed up because the names have been reordered.

One possible solution at least for serial devices (Zsticks, UPS, etc are typically serial devices) could be to use the symlinks in `/dev/serial/by-id/` which typically link back to the ttyUSBxx devices. These are there out of the box (at least on Debian Stretch). Remember to add `EXTRA_JAVA_OPTS="-Dgnu.io.rxtx.SerialPorts=/dev/...` to `/etc/default/openhab`.

**Comment by BClark09** [comment]
My concern with this is that if define a list of `gnu.io.rxtx.SerialPorts` then the serial Library will not find any new ones automatically. There may be a way to fix a single device to `/dev/ttyS*` which will then be picked up automatically by openHAB. I'll need to check this though. As for a way of guiding a user via a script:

- Prompt user to remove all sticks and OK
- Capture list of `\dev\*`
- Prompt user to add a single stick and OK
- Capture list again
- Diff list 1 with list 2
- Use the difference to define a fixed serial port

**Comment by mstormi** [comment]
@holgerfriedrich @ThomDietrich @BClark09 any opinion if and how to proceed ?
I'd stand by my 2019 statement. Nice to have though not essential.
But way too much potential to break things.

**Comment by mstormi** [comment]
So no maintainer really opted in favor of this and as there's no satisfactory (reliable) solution in sight.
Plus in the light of our current refocusing activities to avoid stuff to impact stability, I'll close this one.
