### ISSUE TITLE
Snapshot installs bindings

### ISSUE THREAD

**Issue by hr3** [openhab/openhabian#186]
Installing 2.2 over 2.1 with openhabian-config automaticly installs many uninstalled bindings e.g.
AVM Fritz!Box, Hue, IPP, Sonos, Wemo, etc
and HomeKitIntegrator and HueConnector (maybe because demo-mode).

**Comment by ThomDietrich** [comment]
Hello @hr3 👋 
If demo mode includes all these bindings, yes that would be the case. One could say that's a bug, depending on how you see it. I'd agree, that the initial selection of "demo" should not have this effect later on, **because** you can't switch the initially selected package.

This is unrelated to openHABian. Please create an issue at https://github.com/openhab/openhab-distro

Thanks!
