### ISSUE TITLE
 Not possible to install OH3

### ISSUE THREAD

**Issue by joe197319** [openhab/openhabian#1884]
## Issue information:
I refer to the closed Issue " Not possible to do a fresh install a #1882"
mstormi wrote:
"Please note that this (github) is not the right medium for user support.
Just post on the community forum if you still have issues."

I think it is the right medium here as there seems to be a bug with the parameter
"clonebranch=openHAB3" in openhabian-config as described in the faq
[openhabian-config](https://community.openhab.org/t/openhab-4-migration-faq/148144)

Although I have set the entry "clonebranch=openHAB3" in /etc/openhabian-config the installation ends up with 
an openHAB installation 4.2.0.

I need the version 3.4.4 or 3.4.5 version to import my backup and to do an upgrade afterwards to R4.2.0

## Debug information:
Please provide all of the output provided by utilizing the `debugmode=maximum`
parameter in the `/etc/openhabian.conf` file. For more information on how to
accomplish this, please see [openhabian-DEBUG.md](https://github.com/openhab/openhabian/blob/main/docs/openhabian-DEBUG.md#create-a-debug-log).
```
place logs here
```

## System information:
Please tell us what OS you are running (Raspberry Pi OS, Debian, Ubuntu), what
HW you are running on (Raspberry Pi, amd64). Also include the output of
`cat /etc/os-release` and `uname -m`.
```
place output here
```

**Comment by mstormi** [comment]
This is another user-level discussion that belongs on the forum, but are you aware that `clonebranch=openHAB3` does NOT apply to `/etc/openhabian.conf` as you said you used ? `/etc/openhabian.conf` is only accessible after installation, so that obviously cannot work out that way. You need to edit E:\openhabian.conf right after flashing (E: or whatever the 1st partition of the flashed SD appears as on your Windows).

If you properly did that and nonetheless get 4.2 and if you can actually reproduce & *show* that this is because of a openHABian software bug rather than incorrect usage, please provide the developer-grade information it takes to debug the thing here. 
Post a _comprehensive_ description of what exactly you did to flash and install the system (hw? image name? downloaded when? That's unclear/ambiguous in your old post. Describe files edits you made. manual steps taken to install?), ensure `debugmode=maximum` is also enabled, and provide the full log of your install attempt here that shows what and where install is going wrong (can be found in `/boot/first-boot.log` as explained in the debug guide)
