### ISSUE TITLE
zram not syncing even on shutdown/reboot

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#1899]
see https://community.openhab.org/t/historic-item-states-not-restored-after-reboot/157778/12

I wouldn't know why.
@ecdye could you please have a look and eventually reproduce this? my lab Raspis are out of order ATM.

**Comment by ecdye** [comment]
For sure. From an initial look, it sounds like it might be because of some Pi 5 specific behavior. I'll look into it and try and get it fixed.

**Comment by mstormi** [comment]
I would not think there is anything on OS level that is specific to Pi5 vs. earlier ones that would result in this.

I don't have any Pi5 either to reproduce. Raspi foundation once promised to provide me with one for free but they never sent it. I've just requested it again.

**Comment by ecdye** [comment]
I wouldn't either, however the only reported issues are on Pi 5 and I haven't ever observed issues on a Pi 4

**Comment by ehorvat1** [comment]
I think its not HW related to Raspi 5...see initial openhab community thread... recently Lionello_Marrelli reported issue on Raspi 3, and I on Raspi 4.

**Comment by ehorvat1** [comment]
Ethan, 
sorry since I am no Pro I have questions:
where is the "old" overlayfs binary located and where do I get the "new" one from?

There is a file `overlay` in `/usr/local/bin` ,  a `whereis overlay` shows this location.
But there is no `overlay` in `/usr/local/lib/zram-config` , like in older Openhabians (pre 1.9.1)

Not even sure if you meant the `overlay` file. Probably you meant to delete /usr/local/lib/zram-config ? But this is resulting in zram-config failing to start. Folder /usr/local/lib/zram-config is empty on latest Openhabian.
When I do a `sudo mv /usr/local/bin/overlay /usr/local/lib/zram-config/overlay` the log files complains "overlay not found"   (which no surprize)
After editing line 129 of zram-config , adding the new path /usr/local/lib/zram-config/ the `unrecognized option '--ignore-mounted' `appears again in the log. At least a sign that I am on the used zram-config file.....

**Comment by ehorvat1** [comment]
@ecdye , ! Oh !  now I've realized that you posted actually a link to the `zram.bash` file changes ... answering the questions . Thanks I will test this tomorrow.

**Comment by mstormi** [comment]
@ecdye see #1901 when you build the new image can you check if it comes up with a hotspot on ?
We'll probably have to build another image soon.

**Comment by mstormi** [comment]
please release 1.9.2 when you're done with testing

make sure you include my 2 quick fixes for hotspot, move the v1.9.2 tag forward and build another image before release

**Comment by ecdye** [comment]
Sounds like a plan
