### ISSUE TITLE
raspi-config refuses to uninstall

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#1900]
I merged a quick fix that continues installation once `apt-get purge raspi-config` fails, but we need to investigate why it does.

Can we remove removing raspi-config altogether?

**Comment by ecdye** [comment]
I would think so, IIRC it was only removed in the first place because of the potential of people running it vs. openhabian-config. I think as long as we clearly document that our supported way of making modifications to the system remains using openhabian-config it would probably be fine to let it install.

**Comment by mstormi** [comment]
ok, removed removing it

Fixed-By: https://github.com/openhab/openhabian/commit/058229f44da82c387803a6ef11bdb2d8f3294e36
