### ISSUE TITLE
Nginx / Let's Encrypt: restart webserver after renew

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhabian#210]
It just occurred to me, that the nginx server needs to be reloaded after the certificate was renewed, otherwise the old certificate will be served beyond its age.

@BClark09 can you confirm that?

The solution would be to add either a post-hook or a second command to cron.d/certbot and to certbot.service.

**Comment by BClark09** [comment]
That's eerie, I just this second got complaints from my server about my certificate. Couldnt see anything wrong with certbot and didn't understand it until I saw this, restarted nginx and all works fine again! 

Thanks! Confirmed I guess... :P

**Comment by ThomDietrich** [comment]
Okay then.
I can add a fix next time I'm working on openHABian. Feel free to create a PR if you are quicker. Doesn't seem like an urgent bug

**Comment by ThomDietrich** [comment]
Just ran into this issue once again. :thinking:

**Comment by EliasGabrielsson** [comment]
Maybe rewrite option `$ sudo certbot --nginx` explained here: https://certbot.eff.org/lets-encrypt/debianstretch-nginx.html

**Comment by mstormi** [comment]
@openhab/openhabian-maintainers could anyone please comment if this is still an issue in current openhabian?

**Comment by mstormi** [comment]
@BClark09 do you know if this is still an issue? Ever used certbot --nginx ?

**Comment by BClark09** [comment]
I don't know if issue is a problem any more but I do think the nginx / certificate generation could do with revising. `certbot --nginx` is very helpful but might be difficult script, `certonly` makes this slightly easier.

**Comment by mstormi** [comment]
I'm not 100% up clear how that signing process is supposed to work, but I don't think it's worth the effort.
For the whole signing process to work you need to open port 80. That's beyond our control and remains to be a task that the user has to execute manually every time. At least security-aware people will not keep running with that config.

Just had to renew my certs, too. That worked using certbot --renew, however cron certbot automatism didn't work for me because `/lib/systemd/system` exists on my system (but is empty).

```
[10:08:57] root@openhabianpi:/etc# tail -1 /etc/cron.d/certbot
0 */12 * * * root test -x /usr/bin/certbot -a \! -d /run/systemd/system && perl -e 'sleep int(rand(43200))' && certbot -q renew

```

Can anyone explain the meaning/reasoning for this dir and why it's tested for ?

**Comment by mstormi** [comment]
I'd think the original issue no longer exists and updating to revise the signing process just for the sake of it ain't required.
