### ISSUE TITLE
Missing Linked Things After Reboot Raspberry Pi with Openhabian 1.4

### ISSUE THREAD

**Issue by DJDeepT** [openhab/openhabian#302]
Hello.
Since installing OH 1.4 with Stable 2.2 i see, that some Linked Channels in PaperUI are unlinked after a Reboot. Not always the same things/channels. Different Bindings.

What can i do here? Sometimes i have to restart my pi and then i can't always go through all Things (more than ~130) and check all Linked Items.

Do You Know the Problem?

Thanks

Tobi

**Comment by ThomDietrich** [comment]
Hello @DJDeepT,
sounds like an unpleasant problem you should definitely discuss in the community. I'm not sure what could cause such a situation. In the community please post a clear example of before and after.
You should be able to clearly see what's linked and what is not via the openHAB console.

Anyhow. This error is not openHABian related, hence I'll close the issue here and wish you luck in the community discussion!
