### ISSUE TITLE
WIFI does not work at Raspberry Pi 3 

### ISSUE THREAD

**Issue by Thomase004** [openhab/openhabian#351]
I was send from the openhab board because they could not answer my question yet

https://community.openhab.org/t/wifi-does-not-work-at-raspberry-pi-3/42311/8

Hi,

I´m totally desperate.

I was able to flash my SD card, could install openhabian and could visit the confing menu directly on my Pi and with Putty as well. During the whole time the Pi was connected to LAN and everything worked fine.

Then I tried to switch to WIFI. Therefore I have entered the SSID and my password in the confing menu. I got the message that everything is set up successfully but after a reboot it does not worked anymore. Even with the LAN cable it does not worked.

I formated the SD and tried this procedure twice but it does not work either.

I also tried to change the openhabian.conf before the installation but still no WIFI connection.

Do you have any solution for me?

Thank you in advance!

Thomas

**Comment by ThomDietrich** [comment]
Hello @Thomase004,

I can't think of an obvious reason, besides mistyped password or similar (which I am sure you've typed correctly during your multiple tries).
We had another user once who had a similar issue, turned out that the Pi was not able to connect to the Wifi as the antenna in it is weaker than e.g. in your smartphone or laptop. Please try moving it closer to your AP. Also please try the wifi configuration via openhabian.conf. If the Pi is not online after half an hour, disconnect it and post the content of first-boot.log here.

Good luck!

**Comment by boerreth** [comment]
I download the image yesterday. The same happen to me. Pi does not discover wifi. There is just no wifi

**Comment by small3265** [comment]
@Thomase004 @boerreth @ThomDietrich I'm having the same issue.  I'm running "openhabianpi-raspbian-201712171718-git30faec3-crccc053823".  Openhabian was running like a champ then one day i think it may have run a self update.  Ever since then I couldn't get it to connect to wifi or regular RJ45 copper ethernet.  I decided to re image my SD card to the version that worked from December 2017.  I thought that if i could get it to come back up and i could turn off auto update so it wouldn't break itself again.  Anyway I'm not having any success.  I would like to download the latest and greatest image from this month.  Any ideas when the WiFi issues will be resolved and new updated image released? Thank you.

**Comment by jscottnz** [comment]
Hi there.

I've been trying to setup on a RP3B+ with this image `openhabianpi-raspbian-201804031720-gitdba76f6-crc9e93c3eb.img.xz` and I can not connect either - I am copying the SSID and password directly out of my router setup. 

The first boot log says

```
2018-03-14_00:17:34_UTC [openHABian] Starting the openHABian initial setup.
2018-03-14_00:17:34_UTC [openHABian] Storing configuration... OK
2018-03-14_00:17:34_UTC [openHABian] Changing default username and password... SKIPPED
2018-03-14_00:17:34_UTC [openHABian] Setting up Wi-Fi connection... OK
2018-03-14_00:17:34_UTC [openHABian] Ensuring network connectivity... FAILED

I was not able to connect to the configured Wi-Fi.
Please try again with your correct SSID and password.
Also check your signal quality. Available Wi-Fi networks:
wlan0     Interface doesn't support scanning : Network is down


2018-03-14_00:19:19_UTC [openHABian] Initial setup exiting with an error!
```

My next attempt will be on LAN and i think the wifi won't work after that is set up

**Comment by jscottnz** [comment]
I found my problem - the first time that I saved the `openhabian.conf` file, my editor put in the wrong quotes. These were written to `/etc/wpa_supplicant/wpa_supplicant.conf`

Any subsequent changes to `openhabian.conf` were not written to `/etc/wpa_supplicant/wpa_supplicant.conf` - am I correct in saying that if you make a mistake here you need to reflash? If so I'll see if I can update the docs.

**Comment by jscottnz** [comment]
Just to follow up. it did not work.

also this is questionable

`wlan0     Interface doesn't support scanning : Network is down`

**Comment by jscottnz** [comment]
i made the following change to `/firstboot.sh` and it worked:

```
elif grep -q "openHABian" /etc/wpa_supplicant/wpa_supplicant.conf; then
  echo "$(timestamp) [openHABian] Setting up Wi-Fi connection... OK"
  rfkill unblock wifi
  ifconfig wlan0 up
```

**Comment by small3265** [comment]
@jscottnz thank you! I will give it a try tonight.  So does this force wlan to stay enabled?  Also, what will happen once openhab releases a fix? Will this configuration and thier's conflict with each other?

**Comment by jscottnz** [comment]
ideally if this change is actually required, then we'd get it merged in.

**Comment by ThomDietrich** [comment]
Hey guys!
The "Network is down issue" was already known. @jscottnz great you found the solution!! Please also see #378 
Regarding your quotes and re-edit question: Yes this is currently a known limitation: #273 

We are always thankful for contributions, so please feel free to add a PR. Fyi you'd also need to add this change to https://github.com/openhab/openhabian/blob/master/functions/wifi.sh I presume (near [here](https://github.com/openhab/openhabian/blob/master/functions/wifi.sh#L21)).

**Comment by midhunvnadh** [comment]
I think WiFi is not supported due to your Linux drivers.
You can try watching this

**Comment by rodrob9995** [comment]
Thank you so much it worked for me. It took me a while but what I believe was the issue for me. I had to locate the second IP Adress. Openhabianpi was associated with the Ethernet Port IP address. Once I used the advanced IP Scanner, I saw 2 openHABianPI but 1 for eth0 and the other for wlan0.

To set up. All I did was Flash the openhabian 1.4.1 with Etcher. Added my SSID and PWD on Firstboot.Config using Notepad++ then Copied and Paste @jscottnz (THANK YOU SO MUCH!!)

elif grep -q "openHABian" /etc/wpa_supplicant/wpa_supplicant.conf; then
  echo "$(timestamp) [openHABian] Setting up Wi-Fi connection... OK"
  rfkill unblock wifi
  ifconfig wlan0 up

Disconnected the PWR and Ethernet
Searched for the Second IP Address using Advanced IP Scanner. You will see only 1 stays active.
Use that IP address instead of openHABianPI. For Example HTTPS://192.168.0.39:8080

Also it ONLY worked for me on 2.4GHZ not 5GHZ.
