### ISSUE TITLE
Verifiy WIFI functionallity on RPi3B+

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhabian#378]
Followup to https://github.com/openhab/openhabian/issues/374

Seems like there are still a few issues with the new RPi. @mues-lee, @BClark09 or whoever is willing to: Could you please do a full test of the operation on the RPi3B+, especially wrt the wifi functionality, both during first-boot routine and through the `openhabian-config` option.

Much appreciated!

**Comment by mues-lee** [comment]
Hey @ThomDietrich sadly i will not have much time this week, i will see if I will be able to do it next weekend

**Comment by MZorzy** [comment]
out of the box wifi is soft blocked.
https://community.openhab.org/t/raspberry-3-b-wifi-on-openhabian/43417/23
so
`sudo rfkill unblock wifi`

**Comment by MZorzy** [comment]
#351

**Comment by BClark09** [comment]
I had a bit of time to go through it all

## Install by Ethernet (OK)
A reported warning, but otherwise okay:

| Type | Description | Fix | note |
|-|-|-|-|
| Error | `sed: -e expression #1, char 5: unterminated address regex` |  Change [line](https://github.com/openhab/openhabian/blob/master/functions/system.sh#L137) to use literals (i.e. `'\#^$#d'` | [1] |

## Install by Wireless (FAILED)

Not much to go on here, will be able to diagnose later...

```
2018-04-18_01:09:03_UTC [openHABian] Setting up Ethernet connection... OK
2018-04-18_01:09:03_UTC [openHABian] Ensuring network connectivity... FAILED
2018-04-18_01:10:47_UTC [openHABian] The public internet is not reachable. Please check your network.
2018-04-18_01:10:48_UTC [openHABian] Initial setup exiting with an error!
```

## First Use (OK)

- Switched to snapshot via openhabian-config 
- Installation of Bluetooth binding succeeded and found Pi3 module
- Fronttail/Docs shortcuts working

## Optional Components (OK)

- All components installed successfully, I didn't have the ability use most though.
- Node red comes up with a fair few warnings about running as root, seems to run fine though.
- The FIND installation says that an MQTT broker can't be found, even after installing mosquitto. The server functions correctly with default settings though.

## NGINX (FAILED)

| Type | Description | Fix | note |
|-|-|-|-|
| Error | Issue https://github.com/openhab/openhabian/issues/296 | #PR https://github.com/openhab/openhabian/pull/403 | |

## Purging and reinstalling openHAB (OK)

Only warnings now, still need to implement https://github.com/openhab/openhab-linuxpkg/issues/108#issuecomment-389479817 but this is informative only.

**Comment by BClark09** [comment]
> Install by Wireless (FAILED)

This one was my fault, my edits to `/boot/openhabian.conf` didn't persist. Should probably add a message to the log about deciding to choose ethernet because the string is empty. I can make the PR if others agree? 

I think after the merge of #403 it'll be fine to use with the 3B+.

**Comment by ThomDietrich** [comment]
Hey @BClark09 great help! Thanks!

´sed -i "\#^$#d" /etc/fstab´ is supposed to delete empty lines. It's not really important but otherwise the count of empty lines would increase every time the method is executed. Wdyt? Fix or remove?

**Comment by ThomDietrich** [comment]
Node and root: #247 

Find: could you please create an issue?

> didn't persist. Should probably add a message to the log about deciding ...

I didn't quite get this, so yes please open a PR :)

**Comment by skenmy** [comment]
Just wanted to add a note that I also had to setup WiFi through `sudo raspi-config` before I was able to successfully connect on my 3B+. I set the SSID, Passphrase, and WiFi Country through that tool, `reboot`ed, and the first run script took over from there.

Full steps below:

1. Flash fresh openHABian image to SD card (openhabianpi-raspbian-201804031720-gitdba76f6-crc9e93c3eb.img.xz)
2. Boot 3B+ from flashed SD, observe network error
3. Login on local shell using `openhabian`/`openhabian`
4. `sudo raspi-config` - set Network SSID, Passphrase, and WiFi Country
5. `reboot`

**Comment by bsimmo** [comment]
@skenny, everytime I switch to a new shell and logon it runs the startup script and stops at the error with no place to type raspi-config.  How did you do it ? (I use CTRL+ALT+F# )
  I'm completely new to Openhabian an just had this problem while doing the setup, hence why I'm here. Following a few github links (I'm _not_ new to the Pi or the 3B+)

We need to add a way to set WiFi Country on first boot.  This is a 5GHz restriction from region to region so they had to implement the softblock.
You will also see this problem crop up on the 3A+ (and Ethernet is not an option there)

**Comment by skenny** [comment]
@bsimmo You tagged the wrong person here, sorry!  Paging @skenmy...

**Comment by EliasGabrielsson** [comment]
I think this works now, no one have reported issues on it. Can also verify that wifi installation works on Pi4

**Comment by mstormi** [comment]
Test build complains that `/etc/wpa_supplicant` directory does not exist when script writes into there.
This is probably distribution specific (using balenalib image for the test which may not have all needed packages installed) but we should in any case create the directory if it does not exist.
