### ISSUE TITLE
Lead users to use a secure system

### ISSUE THREAD

**Issue by sysadmama** [openhab/openhabian#381]
Hi,

I'd like to tell you some of my thoughts. I just did a complete fresh install (openHABian 1.4.1) and there are few things I'd like to note.

On login, there's this info thing saying (among other things):
````
The openHAB dashboard can be reached at http://openHABianPi:8080
````

I would prefer to lead the users to use `https://openHABianPi:8443` as there's no reason not to do this... no reason besides...
The docs say the certificate is generated on installing openHAB 2. So why the heck is it generated for `openhab.org`? It will fail on *every* host, right? 😁  Is there a possibility to generate this certificate for `hostname` and `IP_of_system`?

And a last one: when using https://openHABianPi:8443 (after accepting a certificate exception, of course) and doing a standard install, it is not possible to reach `openHAB log viewer` which is running on port 9001: it is hardcoded to `http://openHABianPi:9001`, but I have to use `http://openHABianPi.local:9001`. Unencrypted logfiles in the network, hmm... as it is included in „Standard install“, it should be secured too. What do you think?

I enjoy working with openHABian very much - I think, especially for starters it's a great choice ♥️  Thanks a lot for all your hard work!

Cheers,
  Marianne

**Comment by mues-lee** [comment]
Hi Marianne,

to be honest i don't see the benefits of https over http in an local network.
The main reasons for https, beside google ranking, is to make sure you are talking to the genuine host and privacy of the connection. Both reason are untenable in a local network environment or you should think about whom you allow accessing it.
Also the encrypted transfer of log files shouldn't be a concern for the the same reason and since openHAB does not (yet) support restricting access through HTTP(S) for certain users anyways.

Best
Marcus

**Comment by jpmens** [comment]
It actually is (or should I say "was"?) possible to create your own certificate for openHAB, and I [did this](https://gist.github.com/jpmens/8029383) quite some time ago. You might note that the name of the gist is _holy moly_ ... It's probably easier to run openHAB [behind a proxy](https://gist.github.com/jpmens/8027912) which used to mean fiddling a bit -- I don't know whether that still applies.

That said, I don't see a reason to go to this trouble within a home network in particular not if configuring TLS remains as complicated as it used to be. In addition to that, and as you've correctly pointed out, self-signed certificates are a pain because they dilute the sense of security with people having to "yeah sure, ignore this TLS certificate warning" from every device they use to connect to their stuff.

It's not worth the hassle.

**Comment by ThomDietrich** [comment]
I agree with the others. HTTPS in the local network is not meaningful as long as you don't have a public domain/path linked to it.
As soon as a public domain/path exists you **need** some form of authentication in addition to https and both of this is offered by the reverse proxy option in openHABian.

All the things said above are btw why all of the openHAB documentation, e.g. https://docs.openhab.org/installation/linux.html#package-repository-installation, mentions only the http url and doesn't even bother with the https option of openHAB, which just as well could be disabled by default.

**Comment by EliasGabrielsson** [comment]
I think `let's encrypt +nginx` is the way to go for achieve HTTPS capability. This will enable a seamless experiences with all sort of browsers cert validity checks.

Personally I would say it's preferred to secure internal communication as well as "internal" devices can be hostile as well. For example I do not trust my chinese vacuum cleaner which is an "internal device".

I will close this issue now and details & discussion regarding nginx HTTPS can be found here: https://github.com/openhab/openhabian/issues/327
