### ISSUE TITLE
Switch node.js on armv6l to v8.x branch 

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhabian#388]
See: https://github.com/openhab/openhabian/pull/383

**Comment by brianwarner** [comment]
I've checked this on an RPi2, both upgrading an existing installation and doing the unattended install (cloning a branch from my local fork instead of the upstream master).  Fronttail worked as expected.

Unfortunately my original RPi appears to be bad, and I don't have a zero or a 3.  If anybody is available to test the unattended install on an RPi1, RPi0 or RPi3, here's what you can do:

1. Flash OpenHABian to an SD card
2. Mount the SD card on your computer, and open first-boot.sh in an editor
3. Change this line `/usr/bin/git clone -b master https://github.com/openhab/openhabian.git /opt/openhabian &>/dev/null` to this: `/usr/bin/git clone -b node-carbon-upgrade https://github.com/brianwarner/openhabian.git /opt/openhabian &>/dev/null`
4. Save and exit the file, unmount the card, and boot the Pi
5. Wait a while, then do the Standard setup, wait until the apps are populated, and check if the Log Viewer loads

@ThomDietrich, not sure how much testing you want to do on this before declaring it good. I assume it makes sense to check it works on other Pis?

**Comment by ThomDietrich** [comment]
Hey Brian,
thanks for your efforts! If everything goes well I'd be able to test this in the next two months. Feel free to open a PR. 👍

**Comment by brianwarner** [comment]
Hi Thom, just created the pull request.  Sorry for the delay!

**Comment by EliasGabrielsson** [comment]
we are on node v10.x branch now
