### ISSUE TITLE
Preparations for next milestone

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhabian#401]
@BClark09 @EliasGabrielsson @mstormi @mues-lee @jscottnz @Confectrician @leonsio @brianwarner @kaikreuzer 

Hey guys,
I just wanted to give you a heads up. As openHAB 2.3 is supposed to come out soon, I was wondering if we should provide a new image as well. We already collected a few improvements (like the improved Wifi setup or the WebIF, thanks guys!) and others are still in the making. Now would be the time to think about what we (you?) want to add to openHABian for that new release. If you have any ideas, now would be the time to open an issue, continue discussion or work on PRs. Please comment here with your general ideas.
All contributions from your side would be greatly appreciated!

It might also be worth your while to go through existing issues. Some would be of great interest to the community.

* All Issues: https://github.com/openhab/openhabian/issues
* Milestone image v1.5: https://github.com/openhab/openhabian/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Image+v1.5%22
* This issue needs to be addressed for openHAB 2.3: https://github.com/openhab/openhabian/issues/287

All issues are free to choose, if not otherwise mentioned. If you know of other issues worth fixing till the release, please mention them here so they can be added to the milestone.

Besides that I'd be thankful for other voices in the discussion regarding backups and partitioning, currently led by @mstormi. He has a lot of good ideas and arguments that deserve discussion (see https://github.com/openhab/openhabian/issues/128 https://github.com/openhab/openhabian/issues/399). 

Happy Hacking!

**Comment by BClark09** [comment]
I should be able to resolve https://github.com/openhab/openhabian/issues/285 and finish https://github.com/openhab/openhabian/issues/378. The latter being particularly important.

**Comment by ThomDietrich** [comment]
Thanks @BClark09 !
Btw. I should have mentioned that I will be able to do anything before and shortly after a deadline on June 06.

**Comment by mstormi** [comment]
I think we should do some cleanup on the list of open issues to get a better overview of what's left and possibly important. I started browsing the list and commented on issues that I believe can be closed.

Thomas please also check #171, #147, #144, #105, #49 and close those as no longer relevant if you agree.
#96 I feel to be no good, generally applicable solution, plus it's somewhat superseded by #128.
#44 might still be valid but I don't see the point in investing that much work.
#38 and #10 are obsoleted by frontail, right ?

**Comment by mstormi** [comment]
Ups, now read about your deadline. Ok let's postpone all but the most urgent stuff.

**Comment by EliasGabrielsson** [comment]
@BClark09 @EliasGabrielsson @mstormi @mues-lee @jscottnz @Confectrician @leonsio @brianwarner @kaikreuzer 

Hi everyone!

I will put some effort into trying having an updated release of openhabian done in time with openhab 2.4 release coming up soon. As a first step I have re-prioritized some issues to a 1.6 release to have a tangible goal. My feeling is that we have built up a bit of technical dept since last release which would be nice to have fixed.

I am aware of there is a need of reviewing PR currently.
I have the aim to have a test platform (RPi etc.) running where I will test things out before merging.
That is why things have took some time.

Please join in the effort and we can together build a christmas gift to the community 🎁 !
