### ISSUE TITLE
Possible missing dependency when installing on Stretch

### ISSUE THREAD

**Issue by brianwarner** [openhab/openhabian#478]
I just ran a fresh install on an up-to-day Debian Stretch, on Intel.  At step 03, installing OpenHabian Stable, the installation exited with an error.  Apt suggested installing 'apt-transport-https'.

I believe it would go in `functions/system.sh` in the `basic packages` function.  Before I create a pull request, does this seem right?

**Comment by brianwarner** [comment]
Looking at this with fresh eyes, I think I see the issue.

`apt-transport-https` is installed in the function `needed_packages`, but `needed_packages` is only called when `$UNATTENDED` is true.  It appears to not be installed for an attended installation.

Perhaps a better location than `basic packages` is in `functions/openhab.sh`, just prior to adding the bintray.com/jfrog.io repos?

**Comment by GruensFroeschli** [comment]
Since i've run into this as well:
@brianwarner are you sending a patch?

I think moving this to basic_packages is also wrong because this is also only executed on an unattended installation.

Is there anything against creating a apt-transport-https install function and calling that before any of the other installation functions?
After all calling apt update will always fail as soon as any repository exists which uses https.

I guess this would also solve the issue that apt update is commented out in needed_packages.

**Comment by brianwarner** [comment]
Hi @GruensFroeschli, yep, back from vacation and a pull request is in the queue (#505).  It was a pretty simple one-liner, adding an apt statement right before attempting to add a new repo/key.  I tested it locally and manual installation goes through as expected, now.
