### ISSUE TITLE
Failed installation v1.0 - "dpkg: regarding xxx.deb containing dpkg, pre-dependency problem"

### ISSUE THREAD

**Issue by EliasGabrielsson** [openhab/openhabian#51]
Tried to install the distro according to readme. 
Got hit by a lot of these errors:
```
dpkg: regarding .../dpkg_1.17.27_armhf.deb containing dpkg, pre-dependency problem:
 dpkg pre-depends on libbz2-1.0
  libbz2-1.0 is not installed.
```
I think its best to look at the raw log for precise information.

Hardware: RaspberryPi 2, 16gb sd-card.

[installLog.txt](https://github.com/openhab/openhabian/files/658961/installLog.txt)

**Comment by Firepower** [comment]
Same errors here, RPI3 , 16gb sd-card. Unfortunately no log available

**Comment by ThomDietrich** [comment]
Hey guys, thanks for your issue report.
These log lines are uncritical. See https://github.com/debian-pi/raspbian-ua-netinst/issues/434

However, your installLog.txt ends with
```
[openHABian] Installing additional needed packages... FAILED
```
which is the real problem here. This routine does not do more than [install a few packages through apt](https://github.com/openhab/openhabian/blob/2f1c6c0cfb6aba44c1798ee0d3b945d1f0b7c760/openhabian-setup.sh#L162-L164), I can't think of a reason why this could fail, other than a network error.

@Firepower There should always be a log file, in really weird constellations it's located under ``/boot``.

I've done my last successful installation, as a proof of operation, the day before yesterday. Please check your network connection and restart with a fresh image flash.
Up till this day I and other users in the forum had rarely any problems like this.

**Comment by EliasGabrielsson** [comment]
So the "not installed" statement have nothing to do with dependency for `apt-get install`, are you sure?
I did another reinstallation as I thougth it was network error and get the same errors.

Are there anyway to see the install-log for the part which failed?

**Comment by ThomDietrich** [comment]
This is really unexpected. I've restarted the setup process on my testing Pi.
It's strange that the basic packages are installed but additional packages fail.
Could you please execute the step manually. Just connect per SSH and type:

```bash
sudo apt install raspi-config oracle-java8-jdk apt-transport-https samba bc sysstat avahi-daemon
```

**Comment by ThomDietrich** [comment]
My installation just finished without errors...
```
[openHABian] Installing additional needed packages... OK
```
Please execute the command manually to see which package makes problems for you...

**Comment by EliasGabrielsson** [comment]
Retried installation today and its **works**. 
I wonder if my local `apt-get` servers where down at the installation moments, they had problems before.

Anyway thanks for a great job putting this together Thomas!

**Comment by Firepower** [comment]
After using another sd-card its working now. Seems like the other card is not working anymore which is the reason for no available logs ;-)

**Comment by ThomDietrich** [comment]
@EliasGabrielsson after this incident I realized, that this might indeed be needed:

> Are there anyway to see the install-log for the part which failed?

It's an easy enhancement. I'll look into that.
