### ISSUE TITLE
Install "sudo apt install fontconfig " package

### ISSUE THREAD

**Issue by rstade** [openhab/openhabian#597]
Hi,
I recently did a clean install of Openhabian 1.4.1. When I tried to generate charts with Openhab, I run into an error, which also other Opnhab users observed: see e.g. https://community.openhab.org/t/problem-chart-generation-failed-null/77848.

After I manually installed package fontconfig, chart generation worked immediately.  I propose to add package fontconfig to the next Openhabian release, especially since the root cause was difficult to detect.

Rainer

**Comment by ThomDietrich** [comment]
I remember the issue but why didn't it come up in the openHABian project before? Probabl because almost no user of openHAB really uses the integrated graphing option but goes with Grafana instead :) Maybe this is also a newer issue introduced by the last version of Rasbian? Who knows.

I guess nothing speaks against just installing fontconfig by default. What do the others think?

**Comment by EliasGabrielsson** [comment]
Add `fontconfig` to base installation
