### ISSUE TITLE
User openhabian not created due to failure to detect RPi model

### ISSUE THREAD

**Issue by massimilianocasini** [openhab/openhabian#665]
Hi,

in this image can be an error because the user openhabian is not created. There is only pi user.
There are more error on install log.

Can you check?

**Comment by mstormi** [comment]
This is intentional. What error do you think this creates?

**Comment by massimilianocasini** [comment]
A more scripts during first install to refer to openhabian user.
In documentation there is not any refer to PI user.
So, the openhabian user will be not used?

Il lun 12 ago 2019, 00:29 Markus Storm <notifications@github.com> ha
scritto:

**Comment by EliasGabrielsson** [comment]
> This is intentional. What error do you think this creates?

@mstormi This is _not_ correct. The `openhabian` user shall be created.

@massimilianocasini Hard to say whats went wrong with your installation. Could you try to reinstall it again and see if it works? (Reflashing your image from scratch.)

**Comment by massimilianocasini** [comment]
@elias, I have just tried with the same result. Everyone can see right away
that they can't log in during the first boot to see the log /boot/firstboot
with user openhabian as described.



Il giorno sab 17 ago 2019 alle ore 12:46 Elias Gabrielsson <
notifications@github.com> ha scritto:

**Comment by massimilianocasini** [comment]
There are a more errors during the first boot:

2019-08-17_16:22:56_CEST [openHABian] Adding slightly tuned bash config
files to system... cp: cannot create regular file
'/home/openhabian/.bash_profile': No such file or directory
chown: invalid user: ‘openhabian:openhabian’
OK
2019-08-17_16:22:56_CEST [openHABian] Adding slightly tuned vim config file
to system... OK
2019-08-17_16:22:56_CEST [openHABian] Downloading and setting up
FireMotD... grep: /home/openhabian/.bash_profile: No such file or directory
/opt/openhabian/functions/packages.bash: line 37:
/home/openhabian/.bash_profile: No such file or directory
OK 2019-08-17_16:23:58_CEST [openHABian] Installing Zulu Embedded
OpenJDK... OK
2019-08-17_16:25:16_CEST [openHABian] Installing or upgrading to latest
openHAB release (stable)... OK
2019-08-17_16:26:20_CEST [openHABian] Adding an openHAB dashboard tile for
'openhabiandocs'... OK
2019-08-17_16:26:21_CEST [openHABian] Adding openHAB syntax to vim
editor... chown: invalid user: ‘openhabian:openhabian’
OK
2019-08-17_16:26:21_CEST [openHABian] Adding openHAB syntax to nano
editor... OK
2019-08-17_16:26:22_CEST [openHABian] Adding openHAB scheme to multitail...
OK
2019-08-17_16:26:22_CEST [openHABian] Preparing openHAB folder mounts under
/srv/... OK
2019-08-17_16:26:22_CEST [openHABian] Applying file permissions
recommendations... OK
2019-08-17_16:26:26_CEST [openHABian] Applying miscellaneous system
settings... chown: invalid user: ‘openhabian:openhabian’
OK
2019-08-17_16:26:26_CEST [openHABian] Setting up Samba network shares...
Failed to add entry for user openhabian.
OK

Il giorno sab 17 ago 2019 alle ore 16:24 Massimiliano Casini <
massimiliano.casini@gmail.com> ha scritto:

**Comment by EliasGabrielsson** [comment]
Hmm, I believe you.
We will need to look into this and try to reproduce the error.

**Comment by mstormi** [comment]
> @mstormi This is _not_ correct. The `openhabian` user shall be created.

You're right of course. The only match on "adduser" is in the Dockerfile, though.
That's why we didn't spot this during our testing.
Then again I don't remember taking that out ...
Will reinstall my RPi to find out.

**Comment by EliasGabrielsson** [comment]
Thanks Marcus for checking this out. I don't have any hardware available at the moment.

**Comment by mstormi** [comment]
Did you use the openhabian image ?
My test install is still ongoing but I can already login as openhabian.

**Comment by EliasGabrielsson** [comment]
Good that you verified this. We just need to wait in @massimilianocasini.
Maybe he was using the old pine64 image or the old image. Think it is still linked on the forum.

Closing this now.

**Comment by mstormi** [comment]
yes but what about non-image installs?

**Comment by EliasGabrielsson** [comment]
That will work, the script ask for an username. Maybe not optimal but works.

**Comment by massimilianocasini** [comment]
Hi,

this is the package I installed:

https://github.com/openhab/openhabian/releases/download/v1.5/openhabian-pi-raspbian-201908050414-gitca0976f-crc6a66b5a1.img.xz
I did the installation twice with same problem.
Where am I wrong?

After creating the openhabian user and resolving the permissions,
everything works as before
The user pi in the old version was not created while now yes:

SSH is enabled and the default password for the 'pi' user has not been
> changed.
> This is a security risk - please login as the 'pi' user and type 'passwd'
> to set a new password.


Il giorno sab 17 ago 2019 alle ore 20:43 Elias Gabrielsson <
notifications@github.com> ha scritto:

**Comment by mstormi** [comment]
@EliasGabrielsson 
frankly, I don't understand how and where the openhabian user is supposed to be created.
The code at https://github.com/openhab/openhabian/blob/master/build-image/first-boot.bash#L48 looks strange (that "+x" in particular) to me without that I could tell why exactly.
"username" is taken from openhabian.conf which is "user" there by default.
Seems some twisted mind invented that.... surely not written with maintenance in mind 👎

**Comment by EliasGabrielsson** [comment]
I think we need some input from @ThomDietrich here about the `+x` part.

There are no new user created, the "pi" user are renamed with:

```
usermod -l "$username" $userdef
usermod -m -d "/home/$username" "$username"
groupmod -n "$username" $userdef
chpasswd <<< "$username:$userpw"
```

**Comment by mstormi** [comment]
also noticed "pi" is in /etc/sudoers.d/010_pi-nopasswd but "openhabian" is not

**Comment by ThomDietrich** [comment]
Hey guys, this `+x` piece is higher bash'ery: [Parameter Expansion](http://pubs.opengroup.org/onlinepubs/009695399/utilities/xcu_chap02.html#tag_02_06_02). Here is an explanation and maybe a better option to solve this: https://stackoverflow.com/a/46892617/6654920

The existing main user (pi in the Raspbian case) will be renamed to $username from the configuration file. Not sure why this code would suddenly not work for @massimilianocasini 
Did you change the openhabian.conf file? Your logfile excerpt is missing the "[openHABian] Changing default username and password..." part. Could you post the status from it?

@mstormi 
```
also noticed "pi" is in /etc/sudoers.d/010_pi-nopasswd but "openhabian" is not
```
right. never saw that and depending on what is actually in there, *sudo + no password* doesn't sound like something I'd support 😃

**Comment by mstormi** [comment]
>  `+x` piece is higher bash'ery: Parameter Expansion

I knew but I still didn't get the idea why to replace it with "x".

> sudo + no password doesn't sound like something I'd support 

You want them to type the password on every command ? On a dedicated box no user but you has access to ? Duh, that would drive me crazy.

**Comment by massimilianocasini** [comment]
Any news ?

**Comment by mstormi** [comment]
> 
> 
> Any news ?

No. If there was you would read it here.

**Comment by mstormi** [comment]
> ```
> also noticed "pi" is in /etc/sudoers.d/010_pi-nopasswd but "openhabian" is not
> ```
> 
> right. never saw that and depending on what is actually in there, _sudo + no password_ doesn't
> sound like something I'd support 😃

But it's the Raspbian default so we should not break that i.e. we should add $username to /etc/sudoers.d/somefile

**Comment by ThomDietrich** [comment]
> You want them to type the password on every command ? On a dedicated box no user but you has access to ? Duh, that would drive me crazy.

It's not about that. Default behavior of sudo is that a user has to provide their password once in a session. That is the current behavior and imho a fair security tradeoff.

The default configuration for "pi" on raspbian is to not even ask for the password once. This is...wrong, especially on a system targeting Linux novices. Yes this is my personal opinion but _the internet_ seems to agree https://www.google.com/search?client=firefox-b-d&q=%2Fetc%2Fsudoers.d%2F010_pi-nopasswd

@massimilianocasini wdyt?

@massimilianocasini so far I understood that the user creation (more specifically the renaming of the pi user) should still work as expected. We also didn't see other users running into the issue.
@mstormi  or @EliasGabrielsson would you be willing to implement and test my suggestion for improvement? https://github.com/openhab/openhabian/issues/665#issuecomment-522884304

**Comment by massimilianocasini** [comment]
I only have created another one user called openhabian and set all folders
permission of openhab.



Il giorno lun 16 set 2019 alle ore 11:01 Thomas Dietrich <
notifications@github.com> ha scritto:

**Comment by mstormi** [comment]
Let's not mix issues please.
On sudo default for pi - agree, for the targeted users the requirement to type the password once per session is a fair tradeoff (even if it's a change to Raspbian).
However are you sure it works ? How does openHABian detect a "session" ? I guess you mean a user to "sudo bash" and then type anything else from that shell, right? That however I wouldn't think users are aware of, so the least thing we should do is document that in a prominent location. 

On this issue here @massimilianocasini we believe there's nothing wrong with openHABian at the moment and we don't know what else to look for. Therefore I'd like you to close this issue.
Should you happen to run into this problem again you can open another issue (and provide _first-boot.log_ then please, else it's guessing/dancing in the dark).

@ThomDietrich I support your change suggestion, but why don't you change it yourself?
I've got too many PRs open at the moment I don't want another one to have dependencies.

**Comment by envas** [comment]
I do not understand why the issue should be closed without any action. Saying `we believe there's nothing wrong with openHABian at the moment` is IMO wrong.  

1. The official documentation [here](https://www.openhab.org/docs/installation/openhabian.html) says logon as openhabian:openhabian. I spent a lot of time trying to logon as openhabian, first thinking about disabled SSH or another configuration issue. Only when it didn't work through the console it was clear the user does not exist and I tried it with default raspberry user. 

2. The first-boot.log is full of error messages. Does it mean they can be ignored? Sure, some of them are harmless, like adding openHAB syntax ti the vim editor, but I do not believe you can ignore installation errors like this

```
2019-09-27_16:21:20_CEST [openHABian] Applying miscellaneous system settings... chown: invalid user: ~@~Xopenhabian:openhabiian@~@~Y
```
or
```
2019-09-27_16:21:20_CEST [openHABian] Setting up Samba network shares... Failed to add entry for user openhabian.
``` 

For me, the installation was not properly completed and I am not sure if OpenHAB works as expected. Does Samba work? What are the settings that have not been applied? 

BTW, the primary problem is in the 3rd row of the first-boot.log -> Changing default username and password... SKIPPED. Why SKIPPED?

```
2019-07-10_01:21:33_BST [openHABian] Starting the openHABian initial setup.
2019-07-10_01:21:33_BST [openHABian] Storing configuration... OK
2019-07-10_01:21:33_BST [openHABian] Starting webserver with installation log... OK
2019-07-10_01:21:38_BST [openHABian] Changing default username and password... SKIPPED
2019-07-10_01:21:38_BST [openHABian] Setting up Ethernet connection... OK
```

**Comment by envas** [comment]
A small addendum to my comment. I dived a bit into the source code and here my idea:

The function `functions/helpers.bash -> is_pi()` is pretty important for the decision to rename the default user `pi` while first time booting. The function `is_pi()` parses the content of `/proc/cpuinfo` and analyzes the CPU revision.   

In my case, I am using [Pigeon RB100](http://pigeoncomputers.com/products/pigeon-rb100-cm3/) controller with the [RaspberryPi CM3+](https://www.raspberrypi.org/products/compute-module-3-plus/?variant=compute-module-3plus-32gb) module. This module reports as the revision

```
Hardware    : BCM2835
Revision    : a02100
``` 
I did not analyze the is_pi() function but I assume this revision is not properly recognized and my controller is not classified as RaspberryPi based Linux.

@massimilianocasini : what hardware are you using? An embedded module like me?

Maybe developers should list a set of tested RapberryPi revisions in the openhabian section on the OpenHAB website. One could at least expect issues when using a not certified controller.

**Comment by mstormi** [comment]
>I do not understand why the issue should be closed without any action. 

Then read the full issue history and my statement again. 
Because it works for the vast majority of people and when I tried reproducing.
Because there is no useful information why it does not work in the OP's case that we could act on so there's nothing we can do.

 > I did not analyze the is_pi() function but I assume this revision is not properly recognized and my controller is not classified as RaspberryPi based Linux.
> @massimilianocasini : what hardware are you using? An embedded module like me?

Probably so. And as you do not use a RPi, openHABian behavior - while not intentional - is correct as we aim and state to support RPis.
The code is all there. Simple, readable, plaintext bash. Feel free to submit a PR for your embedded board. Yes this is the only way SW development and testing works, let alone Open Source stuff that people who are not paid for but are spending their spare time for.

> Maybe developers should list a set of tested RapberryPi revisions in the openhabian section on the OpenHAB website.

Maybe users should be a little less demanding and must not omit important information in the first place because they're afraid of us turning their use case down without looking at it or similar. The OP still didn't mention his HW although we asked.
But that's in fact just generating another whole lot of wasted work and leads to frustration on developer side.
As you obviously have the time and knowledge to, please pick and work on any open issue instead of wasting all of our time with a discussion like this. Thank you.

**Comment by envas** [comment]
The thread has 25 comments, two are mine, one of them tried to find the solution. And I am wasting developer's time, not the people commenting out of topic (sudoers)?! 

Only one remark, that I must write, sorry. [CM3](https://www.raspberrypi.org/blog/compute-module-3-launch/) is RPi!  Designed by Raspberry, manufactured by Raspberry, distributed by Raspberry. That's not a clone! Pure RPi, just industrial grade. If you will ignore this brand, you will never cross hobby project borders.   

That's all from me. Sorry for wasting your time.

**Comment by massimilianocasini** [comment]
Hi guys, sorry if my answer was not complete. I'm using a hardware based on
industrial CM3 (https://www.acmesystems.it/CM3-HOME).
Previous versions installed and used on this card have never had problems
and are working properly.
So I conclude that something has been changed in the code.

Grazie

Il giorno sab 28 set 2019 alle ore 21:14 Robert <notifications@github.com>
ha scritto:

**Comment by mstormi** [comment]
> So I conclude that something has been changed in the code.
CM3 is not a supported HW so nothing we cater for and take into account when changing code.
If it has been working in previous versions you have been lucky but now you no longer are, sorry.
You are free to change the code yourself and build your own image (see build.bash) and/or to submit a PR to add support to openHABian, or you can install stock buster Raspbian lite or ARMbian and openHABian as a set of scripts on top.

**Comment by mstormi** [comment]
We do not support neither CM3 nor Pigeon nor any other ARM boards beyond Raspi 2,3,4 because we do not have the HW to test against.
If you submit a PR that makes openHABian _continue_ installing on generic (non Raspi) ARM HW we would include that into our code base I guess but please accept that we will not _support_ your boards.

**Comment by mstormi** [comment]
will add CM1,CM3 support in #861
see if that fixes your issues

**Comment by smithy2167** [comment]
I have the exact same issue, only with an RPi3A+.
I am using the latest 1.5 release.
The only change to openhabian.conf is to add the WiFi credentials.
The first-boot.log shows "Changing default username and password... SKIPPED".
From there, errors occur, it seems because user openhabian does not exist.
When setup has finished, I can only SSH using User: pi Password: raspberry
I can't log in the Samba.  I've tried many combos of user/pass but none work.
I've tried the whole process several times, always with the same outcome.

I've used the exact same file on an RPi0W and it worked perfectly!
So, I'm guessing that the RPi3A+ is not being correctly recognised in the script as a pi?

**Comment by mstormi** [comment]
Please execute this as root:
source /opt/openhabian/functions/helpers.bash
if is_pithreeplus; then echo "identified!" ; fi
grep ^Revision  /proc/cpuinfo


Edit /boot/openhabian.conf and set
clonebranch=stable
debugmode=maximum 
there, then
rm -f /opt/openHAB*; reboot

to trigger another installation attempt, then check first-boot.log for is_pi*

**Comment by smithy2167** [comment]
Thanks for quick response.
It returns "identified" for is_pithreeplus.
Revision is 9020e0.
I'm far from an expert, but is the function is_pithreeplus() in first-boot.bash looking for Revision xxx0dx?

**Comment by mstormi** [comment]
it's looking for revision 0d or 0e, which your box is matching.
So your box is correctly identified hence your problem is not the same as that of the others in this issue.

Read the debug guide, double check openhabian.conf is [up to date](https://github.com/openhab/openhabian/blob/master/openhabian.conf.dist), use debugmode=maximum when installing again and open a new issue with that extended first-boot.log if you're still stuck.

**Comment by mstormi** [comment]
Try the new image from https://github.com/holgerfriedrich/openhabian/actions/runs/153323115

**Comment by smithy2167** [comment]
Thanks.  All fixed.

**Comment by mstormi** [comment]
> Thanks. All fixed.

how? anything we should know about ?

**Comment by smithy2167** [comment]
The fundamental issue I had with the latest 1.5 release seems to be that first-boot.bash contains an older version of is_pi() that doesn't recognise the newer version (xxx0ex) of the RPi3+.  So, user openhabian is not created, causing subsequent problems.

The actions you suggested to edit openhabian.conf and trigger a reboot did result in the board being correctly identified (helpers.bash contains a later version of is_pi() ) and user openhabian being created.  However, trying to sudo gave an error that the user wasn't in sudoers list.  Rather than chase this (and possibly other) problems down a potential rabbit hole, I decided to start again.

Reloading with the new image all worked correctly with the board recognised OK and user openhabian created correctly.

**Comment by mstormi** [comment]
> first-boot.bash contains an older version of is_pi() that doesn't recognise the newer version (xxx0ex) of the RPi3+.

Right, it's the 1yr old version to be distributed with the image and that does not contain the id fix yet which we added recently and which is in the new image. Thanks for digging 'til we found it.

**Comment by atappert** [comment]
I'm getting this openhabian user not existing business on a Raspberry Pi 400.  Sigh.

**Comment by mstormi** [comment]
And I love people only sighing at others' work they use for free but who are unwilling to debug their issue to help in finding the cause although debugging was made as simple meanwhile, see debug guide.

**Comment by atappert** [comment]
No need to be ugly.  I was sighing in frustration at the hours I had already put in trying to make it work.  And it looked like the useful information here eluded to the cause of my issue, in code, which i couldn't figure through.  Having a rough day or something?  Seems like you're projecting some junk at me.  Calling me lazy?  Gtfo and try to consider more than yourself when you post at strangers.
