### ISSUE TITLE
Boot from USB/SSD does not work on Pi 4

### ISSUE THREAD

**Issue by alfista2600** [openhab/openhabian#731]
This is apparently an issue with the firmware of the Pi 4, at the moment (update forthcoming) but in the meantime you might want to warn when using, or disable, the move root to USB drive option in openhabian-config.

My experience is that after running the script, I could neither boot from the SD or the USB-attached SSD with the other storage device detached, and it would hang during boot with both devices attached.

**Comment by tomekz28** [comment]
I confirm that I was unable to move from SD to USB SSD: in fact I was unable to do in on both Pi4 and Pi3B+ with openHABian v1.5. So I am not sure it has to do with the hardware. When I reverted back to openHABian v1.4.1 I was able to move from SD to SDD on Pi3B+ just fine.

**Comment by mstormi** [comment]
This is a RPi or Raspbian topic and as such mostly unrelated to openHABian.
There's PR #758 in the pipe to better explain the "move to USB" menu option and how it relates to ZRAM. It also mentions to check first if your RPi can boot from USB.
But we cannot test all configuration combinations in HW and SW that don't work upfront and warn of anything that might go wrong. That's an ever-moving target probably all users would like us to keep track and care of, but just like the rest of the industry, we cannot accomplish that. It remains every user's responsibility.

**Comment by kevin71246** [comment]
Raspberry Pi is one of the most popular devices people put openHAB on.  I think it would be worth mentioning.  I ran into this, as a NOOB, when I did my very first build last week.  I put a microSD card into a USB reader and plugged it into the PI with the openHABian 1.5 image on it.  It wouldnt install.  Given it was my first time, I had no idea what I was doing wrong.  I ended up trying 1.4 and it worked just fine.  Then I took out the USB reader with the microSD card in it, and plugged the microSD card directly into the Pi - openHABian 1.5 installed just fine.

**Comment by mstormi** [comment]
The most common, working and recommended way of using a RPi is to use the internal SD reader.
No official docs tell you to use an external reader, neither raspberry.org nor openHABian tell you to.
But still you chose to use it.  And now that that obviously didn't work , you *no idea* why it didn't work ? Now come on, that's not lack of documentation, that's a lack to apply common sense.
And no, we cannot and won't make of list of things you should NOT do. We support the most common configuration (internal SD that is) and we tell you to use that
If someone does not want to follow he is free to do that but then he is on his own.

**Comment by kevin71246** [comment]
Love the attitude. Your response definitely makes this sound like a kind, 
helpful community.

This literally was the first time I used a pie. I bought it as a kit that 
came with a USB to sd card adapter, so that's what I used. So yes I 
followed directions and used an sd card. It didn't say adapters aren't 
supported. Sorry my eyes aren't what they used to be...I literally didn't 
even know the PI had a microsd slot. So you're assuming too much (that 
people will only do what YOU would do).

1.4 supports the USB adapter, 1.5 doesn't, it really is that simple. That 
should be documented. What do you tell all the users that easily and 
successfully went from 1.4 to 1.5...and it didn't work?! F it, let's not 
document that lost "feature", let's leave the community in the dark.

Either way, I'm happy that I reported this because I found out I'm not 
there only one, and other people will see this and hopefully it will help 
them. I already fixed it - I was only trying to give back to the community.

Cheers & thanks to all the helpful developers & community that made such an 
awesome solution!

--- Original message ---

**Comment by kevin71246** [comment]
BTW I'm not exactly sure how to determine what THIS issue was created for (1.4, 1.5), but the title says Pi 4; I had the same issue with Pi 3+ and version 1.5

**Comment by mstormi** [comment]
> 1.4 supports the USB adapter, 1.5 doesn't, it really is that simple. That should be documented.

No.  Don't confuse "works" with "supported". If something works it is not necessarily supported.
Supported means it _intentionally_ works like that and we have built code into and/or at least tested openHABian to work with that. 
That we never did with an USB to SD adapter as a boot device because it does not make sense to use such a combination. Nor did we to the best of my knowledge with _any_ USB boot device FWIW. So that never was a "feature" (and so it never got lost).

> So yes I followed directions and used an sd card. It didn't say adapters aren't
supported. 

The list of possible combinations what you buy and use with a Pi is endless. The list of things that are _not_ supported is also endless. So you _CANNOT_ write these lists down.
Sure, we could put your advice into the docs, but then we would also have to put all other similar advice in there, too ... but why bother when we already know that these docs can never become comprehensive because those lists are endless ? Where to start, where to stop ? And your issue is a pretty weird one already, I could think of numerous more issues that are more likely to be hit and thus also would need to find a place in those docs when yours does.
No. Documentation just does not work that way.
And to answer your question: if you or anyone to have this "problem" asked me I'd tell him the same: go put the SD card into the internal reader. And I doubt there's many who have not tried and found out for themselves. As I already said that's the standard way how a Pi is meant to be used and that's how almost everybody uses it.

**Comment by kevin71246** [comment]
Im in no place to dictate what "works" or what's "supported", which is I chose that word and described it that way.

As I indicated, I applied zero thought (to keep myself out of trouble), bought the Raspberry kit, plugged it in and I had this issue.  I'm not sure how you find it such a weird problem.

"That we never did with an USB to SD adapter as a boot device because it does not make sense to use such a combination. " : You know this, I don't. I wish I was as smart as you. But many other users don't know this either. Raspberry Pi, is a hobbist board for both newcomers and seasoned professionals.  You saying "thats how almost everybody uses it" is about as ignorant as it comes - how do you know?  How do you know how many people actually made the same mistake as me?  You dont. You never will.  And people that fixed it either did so on their own, or Googled it and found the problem/fix, but 99% (thats a total guess) of them didn't create a ticket or write a comment.

Perhaps I myself need to spend more time Googling, but its hard to find a list of supported (or "working") devices for Raspberry Pi X and openHABian.  I know you're about to say, oh, the list would be ridiculous...but just 1 or 2 devices that work for each type (yes the internet has enough room for hundreds of devices to be put in a list in a single thread).  This definitely doesnt have to be made by Dev, but the Users could do this as well.  Without anything like this, all we do is guess...like, I need a Zwave USB device, guess Ill buy 10 of them on Amazon and start testing.  There MUST be a better way.  No, I'm not asking for 100% support because a list exists, rather 10 other people that say a particular brand works fine, so its a safe bet.  But you're contagious, I'm getting off track too.

Yes, documentation really does work this way.  Consider this: someone new does something "stupid" (in your opinion) and plugs an sd card into a USB adapter, and cant get openhabian to install.  They Google the issue, and find this ticket.  Then they read this, have to waste a ton of time reading your unhelpful comments, notice that it doesn't work, and boom!  The github ticket tracking and comments resolved their issue.  So just because you refuse to add 3 words to the simple Install, the good news for all the Googlers out there is that theyll find this and have their solution.  Again, that's all I'm trying to do, is help the community.  I am beyond confused on what your role is.

I really don't know why youre trying so hard to prove a point, (no clue what the point is tho)...yet the point is so far off topic from the issue at hand.  They should probably take away your "Helper" badge, and revoke your commenting privileges, because if you read through this thread, see if you can find anything you said that's actually helpful.  

I'm not trying to be mean, but you really are going out of your way to be condescending, unhelpful, and just plain rude.  I believe they call that a Troll. 

Again, the issue was reported, I'm not the only one, and I reported a fix.  I did my role as contributing, have you done yours?

Cheers

**Comment by mstormi** [comment]
>  I did my role as contributing, have you done yours?

Check my profile if you really want to know. I won't comment on the rest, sorry I'm too busy trolling.
