### ISSUE TITLE
[Feature-Request] Keep Certificates through JVM update or Support Manual Re-Installation

### ISSUE THREAD

**Issue by Urmel** [openhab/openhabian#739]
Having a setup that uses self-signed certificates to secure communications, the JVM needs to be made aware of these in order to establish secure connections to other machines. For example, when using influxdb via https.

When updating the JVM, the cacerts file gets overwritten or a the JVM is installed in a new folder that also contains a default cacerts-file.

This results in the need to

1. power down openhab again (and ensure java is down)
2. identify the current correct cacert file location (e.g., _/opt/jdk/zulu8.40.0.25-ca-jdk8.0.222-linux_i686/jre/lib/security/cacerts_)
3. re-import the required certificates into the JVM's cacerts store. (_sudo keytool -import [...]_)

.... could this be made more automatic?
- reminding the user of the issue and asking whether OH shall really be fired up again or manual steps are required
- or re-install all certificates (after asking the user to verfiy fingerprints!) from a defined location in the JVM cacert-store.

**Comment by EliasGabrielsson** [comment]
I think this is part of the core experience of openHABian since mange java is a great part of it. I would like to have this implemented. Do you mind helping out?

**Comment by mstormi** [comment]
We have just inflated the java install process (Zulu 8, 11, Adopt 11 as options) so tracking/building this has just become a lot more difficult.
As I'd say this is merely an edge case (have not heard of anyone else to request that ever since), I don't see the efforts of implementing this are worth spending hence will close this issue.
We'll remain happy to take PRs, of course.

PS: and imho there's little point in encrypting backend accesses
