### ISSUE TITLE
Change to openHAB snapshot fails when not having correct folder permission.

### ISSUE THREAD

**Issue by EliasGabrielsson** [openhab/openhabian#759]
Reproduce:
1. ´cd /sys/bus/w1/devices/[1-wire-device]´
2. Try to change to another openHAB release.
3.  failure as in:

```
$ wget -O openhab-key.asc https://bintray.com/user/downloadSubjectPublicKey?username=openhab 
openhab-key.asc: Permission denied

$ apt-key add openhab-key.asc 
gpg: can't open 'openhab-key.asc': No such file or directory
FAILED (key)

```

**Comment by mstormi** [comment]
You cannot write arbitrary files to that directory no matter what rights you have set because it is an interface to the device driver that only allows for specific file names (= parameters) to be accessed.
BTW you are root.
To me that's user fault, but you could fix that by defining `wget -O /tmp/.somefilename`
