### ISSUE TITLE
add possibility to mount USB storage as log or persistence path to reduce write cycles on the SD card

### ISSUE THREAD

**Issue by FipsJr** [openhab/openhabian#79]

**Comment by robertselberg** [comment]
I found a script called root-ro that I described here: https://github.com/openhab/openhabian/issues/96
It mounts tmpfs as overlay to / which will make all writes to go ram instead of disk. (you lose all changes on reboot).

Maybe this can help.

**Comment by gerritv** [comment]
There is an option to move your entire install to an external USB drive (stick,ssd or hard drive). That would solve your issue.

**Comment by ThomDietrich** [comment]
Just to add an answer to this issue:
Everyone should be aware that the RPi, just as any other computer system, is likely to experience data loss at some point. For the RPi this is more likely than in general. You should therefore implement a backup strategy! openHABian offers Amanda but you can use whatever you prefer (e.g. Duplicati on your main PC).
Read my full discussion of the issue here: https://community.openhab.org/t/openhabian-problem-after-upgrade/23446/8

**Comment by gerritv** [comment]
A backup strategy is always vital to your data safety. Thank you for the hint on Duplicati, Amanda is not a good fit for a mixed Windows/Linux environment (I use Server 2012R2)

**Comment by ThomDietrich** [comment]
@gerritv Amanda stores backups wherever you tell it to, e.g. on a Windows samba share ;)

Anyhow, Duplicati is great, easpecially as it is installed outside the Raspberry Pi and can access everything that is needed via the samba share "openhab-share" provided by openHABian. I use Duplicati for most of my systems.

**Comment by gerritv** [comment]
Mnn, I will see how to configure Amanda to do that. My attempt to use NFS on Server 2012R2 failed. If/when I figure it out I will try to update the 50 option with a Windows target option.
