### ISSUE TITLE
KNX installation not working (anymore)

### ISSUE THREAD

**Issue by StephanSchuster** [openhab/openhabian#85]
I just wrote the following comment to the owner of the underlying install script (currently awaiting moderation):

> Hey,
> 
> your script no longer seems to work since knxd moved to 0.12. Could you please check this? Would be great.
> 
> I came across the issue when using openhabian’s config option “Install KNX” which internally uses your script. This fails due to the above mentioned reason. At least that’s my first guess.
> 
> After adding ‘git checkout tags/v0.10.18 -b install’ after ‘git clone … cd knxd’ in your script, the installation succeeds. However, I guess it’s better to migrate your script to knxd 0.12 (no pthsem dependency).
> 
> Are there any chances that you “fix” this soon? I guess a lot of people are stumbling over this when they want to try out the new openhab 2.0 release via openhabian (+KNX)
> 
> By the way: Thank you for your great work!

**Comment by ThomDietrich** [comment]
Interesting indeed. Please keep me posted. If you do not receive a response in the next few days, please tell me and I'll include a modified version directly in openHABian.

**Comment by tischla** [comment]
Hi,
Script stops with:

checking for LIBUSB… yes
EMI because of usb
checking for ev_run in -lev… no
configure: error: libev not found
make: *** No rule to make target ‘clean’. Stop.


thx
Roland

**Comment by cribskip** [comment]
There are 2 packages missing: libev-dev libev4
Afterwards, after triggering from within openhabian-config, it builds just fine.

KR,
Sascha

**Comment by ThomDietrich** [comment]
@stephanschuster was the script updated or is the solution by @cribskip all that's needed? sure sounds like a clean solution.
@cribskip so adding these to packages to the installation routine is all that's needed?

**Comment by stephanschuster** [comment]
Well, I'm not at home at the moment. So I cannot verify this. But I remember that I definitely installed libev-dev and libev4 and retriggered the install script. Not sure anymore if the build was really successful then. I've tried various stuff meanwhile. In the end I never managed to see KNX packages with knxtool. But that might have other reasons. My setup: RPI3, openHABianpi, knxd, TUL stick with "transparent" firmware.

Regarding the script: I think even if it compiles with libev, it needs to be adjusted a bit. According to the knxd homepage version 0.12 has no more deps to pthsem which is also installed by the script.

**Comment by stephanschuster** [comment]
Even if it might be a bit off-topic: May I ask you guys for help with my personal problem? I think I have a pretty common setup, so other users of openHAB(ian) would benefit from this as well.

My setup:
- Raspberry 3
- [TUL Stick](http://busware.de/tiki-index.php?page=TUL) flashed with "transparent TPUART" firmware plugged into RPI3 and connected to KNX bus (done by my electrician, so should be okay)
- clean install of openHABian
- nothing else has been done (neither on software nor on hardware side)

My expectations:
- install "knxd" (at best via openhabian-config)
- after successful installation "knxtool vbusmonitor1 ip:localhost" on my pi should list some KNX packages when I turn on/off my lights, shutters, ...

Real world:
- I need to adjust the install script to successfully install knxd 0.10.18 or 0.11.18 instead of master (fails)
- Even after successful installation of knxd the command "knxtool vbusmonitor1 ip:localhost" on my pi never brings any output

Questions?
- Are my expectations wrong?
- Is there anything I misundestood?
- Is the "transparent TPUART" firmware the correct one or do I have to use the "FT1.2 serial port BCU" firmware (IMHO not, but I also tried this without success)
- "knxtool vbusmonitor1 ip:localhost" SHOULD list something when I switch lights, right?


Cheers.

**Comment by tatsche** [comment]
I definitely install libev-dev and libev4, but the script fails with the same issue: 

checking for ev_run in -lev... no
configure: error: libev not found

Cheers

**Comment by Zigulle** [comment]
Hallo, 

same here. libel-dev is installed, but the script fails with the same issue:

checking for ev_run in -lev... no
configure: error: libev not found

Greetings

**Comment by ThomDietrich** [comment]
@stephanschuster you can for sure ask these kinds of things. But please not here. You'll reach more people in the community forum https://community.openhab.org/tags/knx

Regarding the issue: Please note, that I myself am not using knx. Hence would be great if you came up with an idea and reported back so i can fix it in script. You should also reach out to the openhab community for help.

**Comment by stephanschuster** [comment]
@ThomDietrich: Sorry for the off-topic post. I moved it to [here](https://community.openhab.org/t/setup-trouble-openhab2-knx-tul-busware-de-knxd/21242) as you suggested.

**Comment by ThomDietrich** [comment]
No problem. It's just more likely to not solve one problem if people start talking about another ;)

**Comment by stephanschuster** [comment]
Okay, for me it's working as expected now.

What I did:
- new clean install of openHABian
- build the latest source code of knxd (0.12.x) exactly as detailed [here](https://github.com/knxd/knxd#building)
- followed the stuff in section "Adding a TPUART USB interface" (due to my TUL stick)
- modified /etc/knxd.conf
- reboot

Done. I can see the packages with knxtool. Perfect. Now I can move on ...

**Comment by stephanschuster** [comment]
Grrr. knxd seems to work but now I cannot access http://openhabianpi:8080/. Connection refused all the time. Even after reboot. Any ideas if and how this could relate to the knxd installation? Unfortunately I did not try to access the webpage before installation of knxd. But in my last installations of openhabianpi it always worked. Some hint on how to debug this?

**Comment by stephanschuster** [comment]
Michael, the author of the install script, updated his script and created a git repo:

> Michael January 30, 2017 at 2:43 PM
>
> Hi Marc,
> i changed the script. Now it should working with knxd v0.12. Version is 0.7.0.
> I also created a repository at github
>
> https://github.com/Race666/install-knxd
>
> Michael

Source: http://michlstechblog.info/blog/raspberry-pi-eibknx-ip-gateway-and-router-with-knxd/

I did not try it. I'm fine with my own compilation. According to some first comments, the script is now working again. Maybe openhabian should use the new git repo for the KNX install script

**Comment by ThomDietrich** [comment]
@stephanschuster as this issue [seems unchanged](https://community.openhab.org/t/setup-trouble-openhab2-knx-tul-busware-de-knxd/21242/5?u=thomdietrich), let's replace the third party script. Would you care to post a script? It could already be fully automatic but any solution I can use is already okay.

**Comment by ferratello** [comment]
Hi, due to a sd-card file system problem I've just "reinstalled" from scratch openhabian (v. 20170218) on my raspberry pi 3.
I had some problem installing knxd from openhabian-config, so I wrote this small script that worked like a charm (for me) [https://github.com/ferratello/knxd_installer](https://github.com/ferratello/knxd_installer) ...
...hope can be helpful.

**Comment by EliasGabrielsson** [comment]
Closing this for having clean issue log.
Track progress in: https://github.com/openhab/openhabian/issues/651
