### ISSUE TITLE
Can't use the openhab console

### ISSUE THREAD

**Issue by sreusr** [openhab/openhabian#86]
using ssh like written to connect locally to the console doesn't work (no reply).
Port is open and java listening to it. Any way to debug?

**Comment by sreusr** [comment]
sorry, works fine

**Comment by ThomDietrich** [comment]
Hey, the ssh host key is generated at first connection. That's why the first or even second attempt will time out. That's something happening on relatively weak systems like the RPi. I'll eventually implement a fix for that. For now, just be patient (as it says in docs [here](http://docs.openhab.org/administration/console.html))

**Comment by sreusr** [comment]
hoi thomas :)

thanks for the clarification and sorry for the "inconvenience", i had to 
wait some more than a few seconds on my rpi 2b+, that made me undetermined.

big thanks for this great work, does the job like a charm!:)
please let me know if i can help you out any how.

best regards,
simeon

ps: i closed the issue by the time of your email, if thats fine for you.


Am 24.01.2017 um 23:36 schrieb Thomas Dietrich:

**Comment by sreusr** [comment]
thanks for the clarification and sorry for the "inconvenience", i had to wait some more than a few seconds on my rpi 2b+, that made me undetermined. big thanks for this great work, does the job like a charm! let me know if i can help you out any how.

**Comment by ThomDietrich** [comment]
Sure thing. You would help a lot if you continued reporting these kinds of details. openHABian is quite young and I wanted to invest some time into usability next
