### ISSUE TITLE
AdoptOpenJDK Option

### ISSUE THREAD

**Issue by ecdye** [openhab/openhabian#868]
So while researching adding AdoptOpenJDK as a Java provider, I became clear that there are two options. I could create a similar routine to what we use for Zulu or I could create a much more complicated script for `apt-get`. While for managing the installs for just AdoptOpenJDK would be fairly easy. Switching between Zulu and AdoptOpenJDK becomes complicated.

Thoughts?

**Comment by mstormi** [comment]
Why would you need a complicated routine for Adopt? If they provide a repo, checking for latest vs. installed version should be left to apt-get instead of doing it manually. Shouldn't that rather ease than complicate the code (in comparison) ?

Why would switching be complicated ? I'd imagine you keep both installed and just run update-alternatives ...

**Comment by ecdye** [comment]
Ah, OK. That is more what I was after. Just keep both installed and run `update-alternatives` then.
