### ISSUE TITLE
[Feature request] Read only filesystem using root-ro

### ISSUE THREAD

**Issue by robertselberg** [openhab/openhabian#96]
This script mounts an overlayfs on the rootfs so that all writes are directed to a tmpfs. I think this could be a nice feature to have to minimize sd card wearing. (maybe it can be enabled/disabled using openhabian-config)

Script: https://gist.github.com/niun/34c945d70753fc9e2cc7

How to install:

    # cd /etc/initramfs-tools/scripts/init-bottom/ && wget https://gist.github.com/niun/34c945d70753fc9e2cc7
    # chmod 0755 root-ro
    # echo overlay >> /etc/initramfs-tools/modules 
    # update-initramfs -u
    # reboot

Done!

**Comment by ThomDietrich** [comment]
Could you please shortly describe which problems you are trying to prevent by making root read-only?

**Comment by robertselberg** [comment]
I believe most people doesn't care about logs but do care about memory card
wearing. This is one way of protecting the memory card.

On Feb 14, 2017 13:58, "Thomas Dietrich" <notifications@github.com> wrote:

Could you please shortly describe which problems you are trying to prevent
by making root read-only?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/openhab/openhabian/issues/96#issuecomment-279700631>,
or mute the thread

**Comment by ThomDietrich** [comment]
Thought so.
SD card wear is a scare story really. It's more important to have a reliable and uninterrupted power supply: http://hackaday.com/2016/08/03/single-board-revolution-preventing-flash-memory-corruption

I did some measurements a while back. Sampled the writes to the SD card on my production openHAB RPi for one week, projected the results up to a year and threw the result at the promised (SanDisk) write cycles of 10'000-100'000. Even when taking the lower end of this plus a small 16GB SD card, the SD card will survive 318 years :boom:

Instead of making your system less flexible and useful by crippling your base, you should invest a few minutes of your time to apply some backup strategy (hopefully a part of openHABian soon).

**Comment by martinjo** [comment]
I`ve been waiting for a solution to the sd corruption problem for quite some time now. Both my own installation has failed (several times with different sd cards) as well as installations I've helped relatives with (much worse as it's hard to fix remotley). Perhaps power loss is part of the problem, but I really think the system should be resilient against that as well. Why is there such resistance against implementing a solution?

**Comment by FulvioSpelta** [comment]
my 2 cent: I think that if are going to use the raspberry in a "production environment" you should use industrial grade SD card. I'm using them on all my "production" raspberry and i've never experienced problems. Yes they cost a lot (almost the cost of the raspberry) but what is the cost of the sd fault ?
"Production" systems need a carefully design (eg: for power supply too), maintenance strategy, security, ecc.; the sd card could be the simpliest problem :-)

Anyway a simple solution that may limit the problem would be interesting.
thx 4 attention

**Comment by robertselberg** [comment]
Making the root fs RO may be a quick fix, but it will solve the problem for a lot of people!
Most people seems to use bad power adapters and cheap sd cards.

**Comment by EliasGabrielsson** [comment]
superseeded by this PR: https://github.com/openhab/openhabian/pull/576
