### ISSUE TITLE
Always use local repo on install?

### ISSUE THREAD

**Issue by ecdye** [openhab/openhabian#986]
@mstormi 

After #961 if I am correct the installer will always use the local repo. This is caused because of this:
``` bash
# must not remove for offline to work
#if [ -d /opt/openhabian ]; then cd /opt && rm -rf /opt/openhabian; fi
# shellcheck disable=SC2154
echo -n "$(timestamp) [openHABian] Cloning myself from ${repositoryurl}, ${clonebranch} branch... "
if ! openhabian_update; then
  echo "$(timestamp) [openHABian] The git repository on the public internet is not reachable."
  echo "$(timestamp) [openHABian] We will continue trying to get your system installed, but this is not guaranteed to work."
fi
ln -sfn /opt/openhabian/openhabian-setup.sh /usr/local/bin/openhabian-config
```
This would work, but `openhabian_update` is defined in `functions/openhabian.bash` which as far as I can tell is never sourced or included in `first-boot.bash` which means that it will always fail and default to the local repo, but this is not the right thing to do because then we won't update to the latest available version when we install from an image.

Is my logic right?

**Comment by holgerfriedrich** [comment]
agree... I reviewed this PR, but did not think of this....

**Comment by mstormi** [comment]
Paste openhabian.bash into first-boot just like we do with helpers ?

**Comment by ecdye** [comment]
I'm not sure that is the best and most correct solution in this case. Additionally, that function is made for a fully setup system, I am not entirely sure that it would work in this case. 

I think that the best approach is to rethink the logic behind cloning the repo. For example, try to clone and if it does not work then default to offline. Another approach is to default to offline install as soon as we can't connect to the network at the very beginning of the `first-boot.bash` script. 

Thoughts?

**Comment by mstormi** [comment]
I'm open to discuss proposals, but I'm wary about any changes to affect repo cloning.
Frankly, openhabian_update() is "high tech" @ThomDietrich invented that I would not feel very comfortable to change or reimplement.
Your proposal more or less is what I used before I moved to call openhabian_update().
[ just that I overlooked that it's unavailable at that time ]
I moved because once I started thinking of the details, there's quite some, and you quickly come to implement them a 2nd time so deduplicating code by using openhabian_update() seemed to be the perfect, elegant solution as it's proven to work so I still like the idea.

**Comment by ecdye** [comment]
I see one issue. The `openhabian-update` function uses many global variables that are not set at the time of install. We would need to write a specifically engineered function just for the install. I feel that in this circuimstance it is not a huge deal to reuse code but make it only for the install. I am doing the same to fix the `Waiting for dpkg/apt to get ready` issue in `first-boot.bash` in my rewrite part two.

**Comment by mstormi** [comment]
didn't get that. Is your suggestion to _duplicate_ the openhabian_update() code or do you want to _reuse_ openhabian_update hence duplicate all those global variable settings we need for that to work?

**Comment by ecdye** [comment]
duplicate but rewrite it to include only the functionality needed in `first-boot.bash`.

**Comment by ecdye** [comment]
Any update on fixing this @mstormi? #946 will depend on a fix for this.

**Comment by mstormi** [comment]
no sorry busy on another front ATM

**Comment by mstormi** [comment]
Ok now looking after this.
I understand current code does not work with Inet *working* because openhabian_update() is missing in first-boot and on initial install boot, /opt/openhabian is NOT there (yet) plus even if it was it would not be sourced.
Am I correct there ?
@holgerfriedrich does /opt/openhabian exist on first boot before the clone attempt?
If so what's wrong with using that ? (yes of course, we would need to source it first)

So Ethan your input I don't understand. Assuming /opt/openhabian is NOT there at install time, I don't think the current *logic* is broken.
We cannot backup /opt/openhabian in that moment cloning fails simply because it isn't there at that stage. We would have to store a copy at image build time and then restore that.
But then we can also use that stored code in the first place .
The current code will continue with first-boot.bash and will do what's possible without Inet, which is exactly what we want it to do.
[ except of course that it does not work ATM as it breaks on calling openhabian_update() ]

I still see the two possibilities discussed above:
A) duplicate the minimum code from openhabian_update into first-boot
I really really DISLIKE that idea because it's code I have not written myself and I don't understand it 100%. That's why I'm so hesitant here. Plus it has some other cons such as code duplication.
B) dynamically copy the code into first-boot at *image build* time and reuse.
[ and as we work on it, we better refactor the current procedure:
insert a line to source all needed *.bash like helpers.bash and openhabian.bash and copy them to /boot or somewhere else on image creation - but NOT store them in /opt/openhabian as if that exists, subsequent cloning will fail).

On B) Ethan you said it wouldn't work because the code uses many global variables. Does it really?
The first thing first-boot does is to copy /boot/openhabian.conf to /etc and to source that, resulting in most globals to be set.
So which variables do you refer to ?

**Comment by ecdye** [comment]
I more meant it probably would not work I did not look at the logic to confirm that theory. If there are issues using `openhabain_update` we can probably adapt it to our needs or rewrite it to be more of a global use. We would also need to remove some of the output about the updates when on the first install using $INTERACTIVE. I'm not sure there is a perfect option in this case but my best guess is that option B will probably result in a better outcome.

That is more of what I meant. I would backup the local copy in a set location in the image and restore and use it if the clone fails.

**Comment by mstormi** [comment]
Ok let's think & test together. Is #996 sufficient ?
A bit difficult to test without having an image to include that.
I think if we write a new image to SD then mount /boot of that and exchange first-boot.bash/add helpers and openhabian that should be a proper test, shouldn't it?
